### ISSUE TITLE
Unmount images while loading

### ISSUE THREAD

**Issue by sospedra** [facebook/react-native#12152]
I'm loading few images per scene but they take a few seconds to load.
That means that in the meantime the user can navigate to another scene.
Causing the images to unmount before they finish loading.
Which triggers the following warning:
`Task orphaned for request <NSMutableURLRequest: [[SOME_HEX_CODE]]> { URL: [[IMG_URL]] }`

It's not crashing. I just want to know if relying the loading cancellation to React unmounting is ok? Having these warning all around is safe?

*Note variables wrapped in [[]]*

**Comment by gp3gp3gp3** [comment]
+1

**Comment by iegik** [comment]
+1

**Comment by myf9000** [comment]
+1

**Comment by cornedor** [comment]
This is also an issue when using FlatList with a list of items that contains images. Because the View gets unloaded all the time when scrolling, you will get a lot of these warnings.

**Comment by shireen** [comment]
+1

**Comment by sporteman** [comment]
+1

**Comment by shireen** [comment]
+1

**Comment by tarang9211** [comment]
+1

**Comment by YangLeoZhao** [comment]
+1

**Comment by dotneet** [comment]
+1

**Comment by zmGitHub** [comment]
+1

**Comment by iegik** [comment]
This will help: https://github.com/kfiroo/react-native-cached-image
It inserts View first, before image loading is complete.
I forked repository (https://github.com/iegik/react-native-cached-image) and try to reach following goals:
- [ ] Customizable image loader (https://github.com/kfiroo/react-native-cached-image/issues/25) (https://github.com/kfiroo/react-native-cached-image/issues/55)
- [x] Cache image request, save on device`s temporary folder
- [ ] Cache with expiration policy (https://github.com/kfiroo/react-native-cached-image/issues/40)
- [ ] Support `304 Not modified` (https://github.com/kfiroo/react-native-cached-image/issues/56)
- [ ] Responsive image (https://github.com/expo/react-native-responsive-image)

**Comment by sospedra** [comment]
Any news from the RN team? :) It's been a loooong time

**Comment by shergin** [comment]
It is community driven project, so PR is always welcome!

**Comment by sospedra** [comment]
Before make any PR I usually wait until one collaborator tell me that's something needed. I'll take your comment @shergin as a call ;)

**Comment by shergin** [comment]
Well, honestly I have no any idea why this happening. But... usually code is worth a thousand words.
Is this expected behavior? Probably not. Someone just have to investigate this.

**Comment by sercanov** [comment]
I had the same issue with FlatList with images on rows. Not only warning but also there are serious performance problems too. I convert it to ListView, its all works great now. There is definitely something going on with FlatList

**Comment by zealot2007** [comment]
+1

**Comment by ray17n** [comment]
+1

**Comment by jing2si** [comment]
+1

**Comment by gelove** [comment]
+1

**Comment by ngankt2** [comment]
+1

**Comment by lh1215** [comment]
+1

**Comment by muygrafico** [comment]
+1

**Comment by MehdiAlouafi** [comment]
+(10/2) / 5

**Comment by noumantahir** [comment]
Having same issues, I am rendering 3 images in a view using images uploaded on cloudinary

**Comment by windhost** [comment]
+1

**Comment by lynrose10** [comment]
+1

**Comment by yangqihua** [comment]
+1

**Comment by arryanggaputra** [comment]
+1

**Comment by nickyhajal** [comment]
I'm also experiencing this while loading images into a flatlist

**Comment by coreycwgriffin** [comment]
+1

**Comment by a3diti** [comment]
+1

**Comment by alexrili** [comment]
+1

**Comment by shiningchen322** [comment]
+1

**Comment by yanyixin** [comment]
+1

**Comment by mowen0303** [comment]
+1

**Comment by Malagasy** [comment]
having a similar issue

it works well on android 6 but ios 11.0 
actually images called with remote uri aren't displaying at all 

has someone found a workaround?

**Comment by Malagasy** [comment]
ok my bad, images were called with http
switching to https worked for me

**Comment by winterbe** [comment]
I'm encountering the same problem after switching from RN 0.48.4 to 0.52.0.

**Comment by pqminh** [comment]
+1

**Comment by ybwdaisy** [comment]
+1

**Comment by ducanhmai205** [comment]
+1

**Comment by congnd** [comment]
+1

**Comment by bunnyc1986** [comment]
+1

**Comment by amerdiglisic** [comment]
+1

**Comment by jvitorr** [comment]
+1

**Comment by jose920405** [comment]
+1

**Comment by AishwaryaSurana** [comment]
@sospedra How were you able to remove this warning? I am facing the same

**Comment by timwangdev** [comment]
```js
YellowBox.ignoreWarnings(['Task orphaned']);
```
@AishwaryaSurana , try this to ignore yellow box warnings.

**Comment by AishwaryaSurana** [comment]
Well @timwangdev this will only hide the warnings, they won't be completely removed

**Comment by alittletf** [comment]
+1

**Comment by mralj** [comment]
+1

**Comment by fryck** [comment]
+1.....

**Comment by weifengzz** [comment]
+1

**Comment by csotiriou** [comment]
+1

**Comment by nicolit** [comment]
+1

**Comment by mrharel** [comment]
+1

**Comment by chen-wen** [comment]
+1

**Comment by pribeh** [comment]
+1

**Comment by Slessi** [comment]
+1

**Comment by adcuz** [comment]
PLEASE use the +1 react feature, it is not necessary to post "+1" and notify everyone who is following the issue.

**Comment by timwangdev** [comment]
I will clean all the “+1” comments, to make this thread more readable.

**Comment by jaderYang** [comment]
Is this a problem that can't be solved?

**Comment by CrazyPython** [comment]
@huitsing @gabegreenberg Are you guys seeing this issue?

**Comment by nateReiners** [comment]
This issue wasn't appearing for me with RN 0.51.0, but now after upgrading to RN 0.55.4 I am seeing these warnings. No flatlist, but I am iterating over a list of images and render them one by one, with each image wrapped in a view.

**Comment by Mimicx** [comment]
i have the same problem, anybody solve this?

**Comment by Sangrene** [comment]
It's weird that this issue is still happening to us after all this time, RN 0.55.4 here.

**Comment by pribeh** [comment]
@Sangrene same here.

**Comment by gabegreenberg** [comment]
@CrazyPython not sure if it is still happening, I haven't been following the project where we noticed this originally, so I'm unsure. @brunolemos have you had any issues as of late?

**Comment by brunolemos** [comment]
> @brunolemos have you had any issues as of late?

@gabegreenberg I don't recall seeing this in the past few months

**Comment by Sangrene** [comment]
Well actually it's causing HEAVY performances drop on large lists.

**Comment by jeffreyrajanofficial** [comment]
Same issue happens after upgrading the RN from 0.47 to 0.56 Any solution to solve this?

**Comment by Sangrene** [comment]
@rayj10 I switched to https://github.com/Flipkart/recyclerlistview/ as it has better performance overall.

**Comment by tonmanayo** [comment]
any fixes for this yet??

**Comment by MuhamedAhmed24** [comment]
the same here :S

**Comment by connect-dev** [comment]
If instagram, snapchat, gmail were all developed using react native, how they are addressing this task without any issue?

**Comment by csotiriou** [comment]
Actually, I am using FastImage to render cells with images (approx 500-600) using a FlatList. I strongly recommend using that instead of RN's image

It helps if "removeClippedSubviews" is true.

**Comment by tkserver** [comment]
@connect-dev I bet server side rendering helps a lot.

**Comment by yuezonglun** [comment]
Encountered the same problem

**Comment by santiph** [comment]
Same problem. Any updates from RN team?

**Comment by cglacet** [comment]
I have also have the warning, but the image displays normally. Maybe the warning shouldn't be there? I had the same code for a while and this is the first time I get this warning.

**Comment by michalchudziak** [comment]
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗

**Comment by bondparkerbond** [comment]
I encountered a similar YellowBox warning that was unrelated to loading images in my App. Instead, in dev mode on react-native 0.59, I had some console.warn statements that have a spinner while the Source Map loads that is replaced with a Check Mark. As far as I can tell, even though the check mark always appears, it sometimes triggers the Task orphaned for request YellowBox when the transition between spinner and check mark occurs and may be related to communication delays/timeouts on the bridge between the physical device(in this case iPhone SE) and the react-native packager running on your computer. In my case it is not related to any in app image loading or network calls, as I was using a hard coded object and some console warning to validate some sanitization I was doing to make sure I was getting the correct info from an expected API call without needing to worry about actually hitting the API. It also usually only appeared after several occurrences of making changes, shaking my device, clicking Reload, and running the changes before the YellowBox with:

Task orphaned for request: <NSMutableURLRequest: 0x1c001c650> { URL: data:image/png;base64, ...
... rAndOmAlphaNuM3rics ... RK5CYII== }
appeared. I also seemed to need to have the YellowBox expanded when the spinner changed to a check mark for it to appear. Restarting the packager and the app seemed to fix my issue for a while, although I am unsure if this is the same issue others are seeing or related to some other issue.

**Comment by xaphod** [comment]
I am seeing this in RN 0.59.8 with an Image trying to load from a file:// URI (on disk) shortly after startup. The image does not load, which means I cannot ignore the warning. The file is fine.

YellowBox.js:67 Task orphaned for request <NSMutableURLRequest: 0x2835edb50> { URL: file:///var/mobile/Containers/Data/Application/1AD76457-FB51-49B3-9965-92E555C8EA7E/Documents/photo.jpg }

**Comment by anhnh27** [comment]
> I am seeing this in RN 0.59.8 with an Image trying to load from a file:// URI (on disk) shortly after startup. The image does not load, which means I cannot ignore the warning. The file is fine.
> This is on an iPhone XS with iOS 12.3.1. The XS is fast enough that it exposes race conditions in unusual places (from my experience as a native iOS dev)
> 
> YellowBox.js:67 Task orphaned for request <NSMutableURLRequest: 0x2835edb50> { URL: file:///var/mobile/Containers/Data/Application/1AD76457-FB51-49B3-9965-92E555C8EA7E/Documents/photo.jpg }

@xaphod  Did u find any solution?

**Comment by Elias-Graf** [comment]
Still an issue for me on `react-native: 0.61.5` anyone else?

**Comment by FrancisKoya** [comment]
Sill facing this issue for ios.

**Comment by shivam4ukhandelwal** [comment]
Hi,
is there anybody is going to solve this ???
cause, I think it makes an effect on the performance of flatlist.
