### ISSUE TITLE
Upgrading to io.js and Node.next

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1737]
io.js is the modern version of Node for practical intents and purposes and is way ahead since it uses a maintained version of V8 that is faster and has ES6 features, and the Node talent is almost totally focused on io.js.

The two projects are planning to converge by using the Node.js name and the io.js codebase, roughly speaking, so a future version of Node (ex: Node 3.0) will be running io.js under the hood. So insofar as skating towards where the puck will be is a good thing it makes sense to target io.js. This is a list of things I think need to happen for the upgrade:

- [x] Upgrade npm deps to their latest versions that support io.js
  - [x] jest 0.5.x (branch is here https://github.com/facebook/jest/tree/0.5.x)
    - upgrades jsdom to 5.x which dropped support for old Node, and also drops dependency on contextify since it's built into io.js's vm module... really speeds up npm install
  - [x] ws 0.7.x (#1738)
  - [x] stacktrace-parser should support node 1.x and 2.x in its package.json's "engines" field (https://github.com/errwischt/stacktrace-parser/pull/2, #1738)
- [x] get tests passing on io.js (#1382)
- [x] update .travis.yml to use iojs-v2 instead of node (#1382)
- [x] update installation docs to say `brew install iojs` or nvm (nvm is super great but requires a little more setup) (#1802)
- [x] make podspec install only production dependencies for an easier migration (#1803)
- [ ] [optional] can drop promise library from the packager's dependencies since Promise is built in
- [x] measure perf changes in the packager cc @amasad -- the diffs to get jest running on io.js [improved perf by over 30% when running its own tests](https://github.com/facebook/jest/pull/374#issuecomment-112642386)
- [ ] Raise awareness around upgrading to io.js with a banner message (#1824)

**Comment by ide** [comment]
Some rough perf numbers:

```js
function run() {
  var reactNativeRoot = path.resolve(__dirname, '../react-native');
  var startTime = Date.now();
  return ReactPackager.buildPackageFromUrl({
    assetRoots: [reactNativeRoot],
    blacklistRE: blacklist(false),
    cacheVersion: '' + mathjs.randomInt(10, 1000000000),
    transformModulePath: path.join(reactNativeRoot, 'packager/transformer.js'),
    projectRoots: [reactNativeRoot]
  }, '/Examples/UIExplorer/UIExplorerApp.ios.includeRequire.runModule.bundle?dev=false&minify=true')
  .then(function() {
    console.log(Date.now() - startTime);
  });
}
```

- io.js 2.3.1: ~5900ms (median-ish after running it a couple times)
- Node 0.12.4: ~6300ms
- Node 0.10.38: ~6400ms

**Comment by ide** [comment]
We're in good shape now. The websockets module just added support for io.js 3.x, which means it should work out of the box with Node 4 coming next month.
