### ISSUE TITLE
0.8.0-rc

### ISSUE THREAD

**Issue by ide** [facebook/react-native#1864]
These are the commits we should get into master before cutting 0.8.0-rc.

- [ ] Upgrade two npm deps to work better with io.js: #1738 
- [x] Update docs with instructions for installing io.js: #1802
- [x] Print a notice if the user is not running io.js: #1824 
- [x] Remove unnecessary imports for RCTHTTPRequestHandler to fix Cocoapods build: #1865

These are dependent issues: 
- ~~Expose more modules when it is sensible to do so, due to new packager behavior #1821~~ This will not be included in 0.8.0-rc, waiting for @vjeux's return from pto before proceeding

**Comment by grabbou** [comment]
Nice! Any chances text enhancements are merged as well? (text-decoration)

**Comment by ide** [comment]
@grabbou textDecoration will be included along with a bunch of other updates. Should be an exciting release.

**Comment by ide** [comment]
https://github.com/facebook/react-native/releases/tag/v0.8.0-rc
