### ISSUE TITLE
$FlowFixMe - TODO T29156721 `React.forwardRef` is not defined in Flow, yet.

### ISSUE THREAD

**Issue by ggtmtmgg** [facebook/react-native#22595]
- [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native release: https://github.com/facebook/react-native/releases

## Description
I found this comment out and I'm wondering I should remove this comment out or fix something.

```
    // $FlowFixMe - TODO T29156721 `React.forwardRef` is not defined in Flow, yet.
    ViewToExport = React.forwardRef(View);
    ViewToExport.displayName = 'View';
```
https://github.com/facebook/react-native/blob/v0.58.0-rc.1/Libraries/Components/View/View.js#L50-L52

Because `React.forwardRef()`'s arguments are defined in React v16.6.3.
```
export default function forwardRef<Props, ElementType: React$ElementType>(
  render: (props: Props, ref: React$Ref<ElementType>) => React$Node,
) {
```
https://github.com/facebook/react/blob/v16.6.3/packages/react/src/forwardRef.js#L12-L14

May I have some info about this comment out? @yungsters

**Comment by evanjmg** [comment]
I'm having this issue with typescript and react native
