### ISSUE TITLE
React Native London Issue Triage

### ISSUE THREAD

**Issue by cpojer** [facebook/react-native#24032]
**Goal:** Reduce open issues on the React Native repository by resolving, fixing, closing and otherwise handling existing issues in a way that is satisfying to our users.

**Time:** Tuesday, March 19th

**Approach:** Split into groups of 3-4 people based on (mixed or common) expertise and assign a bucket of issues to work on throughout the day. We aim to leave a comment on 60-70% of all open issues with further steps. Make sure you learn something from others and have fun!

## Proposed Flow

* Sit together in a group of 3-4 people, organize in any way you prefer.
* Try to go through as many issues as possible throughout the day.
* Be as nice as possible in your replies.
* Leave a comment on every issue that you are looking at.
* **Sweep:** Divide the issues and go through them individually. Handle the easy ones first, and note the harder ones to work on together later.
* **Check** handled issues from the issue triage bucket.
* **Encourage** people to send Pull Requests with fixes, even if we close things.
* **Ask** for a repro and **add the “Resolution: Needs Repro”, “Follow-up”** label.
* **Add high-pri tag** if issue requires fixing within the next month
* **Add low-pri tag** if issue is not important enough for us to be fixed within the next three months
* **Add mid-pri tag** if in between
* If **you are unsure**, ask for a follow-up from the author. **Add the “Follow-up”** label so that somebody from FB can check the issue in a few weeks.
* **Move** if the issue is related to something in a community repo
    * Send a message to @cpojer with the issue id + the repo it should be moved to.
* **Escalate to FB employees** if it requires attention by FB
* **Close** if
    * …the last comment is asking for a repro and is older than a week
    * …the issue is no longer relevant (ie. extraction of the module through lean core, removed feature, etc.)
    * …the issue does not reproduce
    * …the issue has had no activity for a while
    * …the issue was created prior to 0.57 and had little interaction since

## People

|Team	|Name	|Alias	|
|---	|---	|---	|
|The A-Team	|Lorenzo Sciandra	| @kelset	|
|The A-Team	|Eli White	|@TheSavior	|
|The A-Team|Mike Diarmid	|@Salakar	|
|The A-Team|Thibault Malbranche	|@Titozzz	|
|Mike Drop	|Orta Theroux	|@orta	|
|Mike Drop	|Mike Grabowski	|@grabbou	|
|Mike Drop	|Rick Hanlon	|@rickhanlonii	|
|X	|Christoph Nakazawa	|@cpojer	|
|Closers	|Michal Pierzchala	|@thymikee	|
|Closers	|Bartol Karuza	|@bartolkaruza	|
|Closers	|Eloy Duran	|@alloy	|
|Turbo	|Dulmandakh Sukhbaatar	|@dulmandakh	|
|Turbo	|Ferran Negre	|@ferrannp	|
|Turbo	|Michal Chudziak	|@michalchudziak	|

## Issue Buckets

Issues are bucketed in a way so that every team receives roughly the same set of issues from high engagement to low engagement.

* The A-Team: #24028
* Mike Drop: #24029
* Closers: #24030
* Turbo: #24031

## Canned Replies

Use these for your replies if you like.

### Upgrading to 0.59

```
Hello there 👋 this issue seems to be related to your experience upgrading between versions. We know this has been a [long lasting pain for the community](https://github.com/react-native-community/discussions-and-proposals/issues/68) so starting v0.59 we have introduced a new flow via the [new CLI](https://facebook.github.io/react-native/blog/#cli-improvements).

To upgrade to that version, you may still need to do some manual steps – we suggest you use [rn-diff-repo](https://github.com/pvinis/rn-diff-purge) to accomplish this.

Given that this is not strictly a bug with the library itself I'll close this, but if someone can create a repro that has this issue with a freshly created `react-native init` project we can reopen it and discuss it further 🤗
```

### There is no repro / don't want to post repro

```
Hello there 👋 this issue doesn't have a repro (which means, a `react-native init`-ed project with the minimal changes that leads to creating the same issue you are reporting). Unfortunately, I have no way of helping you in a meaningful way – there is no easy way for me to recreate the situation and check that the issue reported is still there when changing the code.

Because of this, we are going to close this issue - but if a repro is shared, we are happy to reopen it 🤗
```

### Issue is stale / There has been no activity

```
Hello there 👋 this issue seems to have been inactive for the past few weeks. Because of this, it's likely that the issue is not a high priority anymore or it has been solved by OP; for these reasons, we'll close it. But please, if it's actually still an issue with 0.59 please comment below and we can reopen it or please send us a Pull Request with a fix 😊
```

### Issue can't be reproduced

```
Hello there 👋 by using the repro / the list of steps to reproduce, we can't actually see the reported bug on RN 0.59 so we'll close this issue. It may have something to do with your local setup, please double check that you are using the correct version of Android Studio / XCode / Android NDK / Yarn / etc.
```

### Issue is on old version

```
Hello there 👋 this issue has been reported for an old version of React Native. Ideally we'd like everyone to be using 0.59 (see the [awesome changes](https://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059) it brought) but we know updating can be a pain. We are going to close this issue because it's from a version before 0.57, which is really old.

But please, if it's actually still an issue with 0.59 please comment below and we can reopen it. Even better, please send us a pull request with a fix 😊
```

### Issue is a feature request

```
Hello there 👋 this issue seems more of a precise feature request than a bug report. For this reason, we'd prefer for you to post it to [Canny](https://react-native.canny.io/feature-requests) so that it can be prioritized against the FR already there (maybe someone already submitted it!).
```

### Issue is a discussion or proposal

```
Hello there 👋 this issue seems more of a long form conversation to be had; for this reason, we'd prefer to migrate it to the dedicated [discussion-and-proposals](https://github.com/react-native-community/discussions-and-proposals/) repo so that it won't be lost in the noise of the many bug reports being submitted.
```

### Issue is super inactive

```
Hello there 👋 this issue seems to have a really low activity on it. This is probably because OP managed to find a solution - also, it was most likely related their precise configuration. Because of this inactivity, we are closing it - but please feel free to comment and post a repro for version 0.59 and we'll gladly re-open it 🤗
```

**Comment by cpojer** [comment]
Discussions to be handled by FB:
### Discussions
 - [ ] #23313 [☂️ Lean Core](https://github.com/facebook/react-native/issues/23313), 118 comments, 198 reactions, Created: 2/6/2019, Last Commented: 3/18/2019
 - [ ] #8024 [[ScrollView] Add support for nested scrollable vie](https://github.com/facebook/react-native/issues/8024), 45 comments, 178 reactions, Created: 6/9/2016, Last Commented: 9/20/2018
 - [ ] #19297 [[META] Roadmap of future Android(s)](https://github.com/facebook/react-native/issues/19297), 34 comments, 24 reactions, Created: 5/16/2018, Last Commented: 3/18/2019
 - [ ] #15371 [React Native Performance Profiling](https://github.com/facebook/react-native/issues/15371), 12 comments, 62 reactions, Created: 8/4/2017, Last Commented: 11/6/2018
 - [ ] #10966 [Official, gradual path to RN packages not publishi](https://github.com/facebook/react-native/issues/10966), 27 comments, 18 reactions, Created: 11/16/2016, Last Commented: 2/7/2019
 - [ ] #19573 [☂️ Supporting Xcode 10 and the new Xcode build sys](https://github.com/facebook/react-native/issues/19573), 18 comments, 31 reactions, Created: 6/5/2018, Last Commented: 11/2/2018
 - [ ] #13094 [Remove react-native package from maven central and](https://github.com/facebook/react-native/issues/13094), 28 comments, 7 reactions, Created: 3/22/2017, Last Commented: 5/16/2018
 - [ ] #19991 [[META] Kotlin in React Native](https://github.com/facebook/react-native/issues/19991), 13 comments, 32 reactions, Created: 7/1/2018, Last Commented: 1/20/2019
 - [ ] #22989 [[React Fabric] Updating Build Configuration (Cocoa](https://github.com/facebook/react-native/issues/22989), 21 comments, 7 reactions, Created: 1/15/2019, Last Commented: 3/7/2019
 - [ ] #22609 [☂️ Resolve Warnings in Xcode](https://github.com/facebook/react-native/issues/22609), 2 comments, 27 reactions, Created: 12/11/2018, Last Commented: 2/26/2019
 - [ ] #20302 [[META] Upgrading Folly](https://github.com/facebook/react-native/issues/20302), 13 comments, 2 reactions, Created: 7/19/2018, Last Commented: 10/30/2018
 - [ ] #23112 [[META] AndroidX migration plan](https://github.com/facebook/react-native/issues/23112), 7 comments, 10 reactions, Created: 1/23/2019, Last Commented: 2/20/2019
 - [ ] #19650 [createAnimatedComponent should use forwardRef ?](https://github.com/facebook/react-native/issues/19650), 9 comments, 1 reactions, Created: 6/11/2018, Last Commented: 2/5/2019
 - [ ] #23561 [☂️✅ Green CI: Fix and re-enable tests on Circle CI](https://github.com/facebook/react-native/issues/23561), 8 comments, 3 reactions, Created: 2/20/2019, Last Commented: 3/11/2019
 - [ ] #22800 [[Bug]RNTester debug break in master](https://github.com/facebook/react-native/issues/22800), 6 comments, 4 reactions, Created: 12/26/2018, Last Commented: 1/16/2019
 - [ ] #13187 [[Flow] react-native FormDataPart type conflicts wi](https://github.com/facebook/react-native/issues/13187), 2 comments, 8 reactions, Created: 3/28/2017, Last Commented: 3/8/2018
 - [ ] #19736 [Supporting custom fonts the Android Way](https://github.com/facebook/react-native/issues/19736), 5 comments, 2 reactions, Created: 6/15/2018, Last Commented: 11/16/2018
 - [ ] #21407 [Allow for Text components to support a forced mini](https://github.com/facebook/react-native/issues/21407), 5 comments, 2 reactions, Created: 9/28/2018, Last Commented: 10/9/2018
 - [ ] #23332 [Introduce code quality tools for android.](https://github.com/facebook/react-native/issues/23332), 4 comments, 1 reactions, Created: 2/7/2019, Last Commented: 2/9/2019
 - [ ] #22778 [["Discussion"] Remove android platform and platfor](https://github.com/facebook/react-native/issues/22778), 4 comments, 0 reactions, Created: 12/24/2018, Last Commented: 2/3/2019
 - [ ] #22779 [Add CI file in template](https://github.com/facebook/react-native/issues/22779), 4 comments, 0 reactions, Created: 12/24/2018, Last Commented: 2/3/2019
 - [ ] #22873 [Build script finding incorrect version of shasum](https://github.com/facebook/react-native/issues/22873), 1 comments, 2 reactions, Created: 1/4/2019, Last Commented: 1/29/2019
 - [ ] #23469 [chore: cost of dependencies in react-native](https://github.com/facebook/react-native/issues/23469), 1 comments, 2 reactions, Created: 2/14/2019, Last Commented: 2/14/2019
 - [ ] #24016 [Discussion: removal of accessibilityComponentType](https://github.com/facebook/react-native/issues/24016), 2 comments, 0 reactions, Created: 3/18/2019, Last Commented: 3/19/2019
 - [ ] #21303 [":CFBundleIdentifier", Does Not Exist - Mitigating](https://github.com/facebook/react-native/issues/21303), 1 comments, 0 reactions, Created: 9/24/2018, Last Commented: 1/21/2019
 - [ ] #23665 [jsi::runtime::evaluateJavaScript can not evaluate](https://github.com/facebook/react-native/issues/23665), 0 comments, 0 reactions, Created: 2/27/2019
 - [ ] #23946 [Discussion: How to run shell/Command Line Program/](https://github.com/facebook/react-native/issues/23946), 0 comments, 0 reactions, Created: 3/15/2019
 - [ ] #23999 [how can i solve this issue](https://github.com/facebook/react-native/issues/23999), 0 comments, 0 reactions, Created: 3/18/2019
 - [ ] #24008 [App Startup Time Benchmarks](https://github.com/facebook/react-native/issues/24008), 0 comments, 0 reactions, Created: 3/18/2019

**Comment by cpojer** [comment]
This was an incredibly successful day. We started with ~680 open issues and finished just shy of 400 issues. Thank you so much to all the people from the A-Team, Mike-Drop, Closers and Turbo teams who spend a full day triaging and handling issues. We are now gonna go for a nice dinner together, I think we deserve it :)

**Comment by orta** [comment]
![2019-03-19 17-51-07 2019-03-19 17_52_09](https://user-images.githubusercontent.com/49038/54629558-bcbf7500-4a6f-11e9-94da-5c766f0ac4d6.gif)
