### ISSUE TITLE
[standards] Umbrella issue to track migration to standard path-based requires (remove Haste)

### ISSUE THREAD

**Issue by ide** [facebook/react-native#24316]
This issue tracks commits that rewrite `require()` calls to use standard module paths instead of Haste module names. This brings the RN repo closer to how the React repo is set up, and also opens the door for greater compatibility with the last 10 years of tooling that uses path-based module locations, and eliminates the entire class of issues related to the Haste map outside of the Facebook context.

All modules in the RN repository will still be requireable via Haste. That is, if there's Facebook application code that uses Haste, there will be no change.

This is a spiritual continuation of https://github.com/facebook/react-native/issues/18598, which has more technical details. 

- [x] Let Flow support Haste & Node simultaneously for now (pre-req): ~https://github.com/facebook/react-native/pull/24318~
- [x] RNTester: ~https://github.com/facebook/react-native/pull/24317~
- [x] RNTester (TurboModules): ~https://github.com/facebook/react-native/pull/24754~
- [x] Code under the Libraries directory: ~https://github.com/facebook/react-native/pull/24749~, ~https://github.com/facebook/react-native/pull/25001~
- [x] IntegrationTests: ~https://github.com/facebook/react-native/pull/24750~
- [x] Jest setup script: ~https://github.com/facebook/react-native/pull/24753~
- [x] androidTest JS: ~https://github.com/facebook/react-native/pull/24813~
- [x] Vendored libraries (~https://github.com/facebook/react-native/issues/24769~): ~https://github.com/facebook/react-native/pull/24807~
- [x] React renderers (~https://github.com/facebook/react-native/issues/24770~): ~https://github.com/facebook/react-native/pull/24782~, ~https://github.com/facebook/react/pull/15604~, ~https://github.com/facebook/react-native/pull/25100~, ~https://github.com/facebook/react/pull/15786~
- [x] react-native-implementation (~https://github.com/facebook/react-native/issues/24771~)
- [x] Lint rule to prevent more Haste: ~https://github.com/facebook/react-native/pull/25058~
- [x] Disable Haste outside of Facebook (~[Jest hasteImpl](https://github.com/facebook/react-native/issues/24772)~, .flowconfig, Metro): ~https://github.com/facebook/react-native/pull/24809~ (Jest mocks), ~https://github.com/facebook/react-native/pull/24811~ (Jest hasteImpl), ~https://github.com/facebook/react-native/pull/24812~ (.flowconfig), ~https://github.com/facebook/metro/pull/410~ (Metro default providesModuleNodeModules)

---

# Draft Announcement Notes

## Replacing Haste with standard imports

In the 0.61 release of React Native, we are internally replacing "Haste"-style module imports with standard path-based imports. Instead of `require('View')`, React Native will internally use `require('./View')`. Haste is a proprietary module system with a global namespace that is used within Facebook. Path-based imports are used by [browsers](https://developers.google.com/web/fundamentals/primers/modules), [Node.js](https://nodejs.org/api/modules.html), and various tools and libraries in the greater JavaScript ecosystem. Moving to the standard means React Native will be more compatible with the ecosystem. Also, this creates a path to optimize the bundling step, as the bundler no longer needs to scan all files to create the Haste module map.

Some out-of-tree implementations of other platforms, like [React Native Windows](https://github.com/Microsoft/react-native-windows), may be affected by this change if they rely on overriding files using overlapping Haste module names. There are two potential solutions for maintainers of platforms like this.

### Vendoring React Native

One solution is to follow [React Native for Web](https://github.com/necolas/react-native-web/)'s approach of [vendoring (copying) React Native's code](https://github.com/necolas/react-native-web/tree/master/packages/react-native-web/src/vendor) into the out-of-tree platform repository. This approach is also more future-proof and works if React Native were to publish itself as a single "flat bundle" in the same manner as React, which would also be a breaking change for out-of-tree platform implementations. It also simplifies the work required if React Native were to rely on the JS interpreter's built-in import/export module system, which does not implement Haste.

React Native for Web's entry point (`index.js`) exports web-specific implementations of all the public APIs in React Native. But, sometimes, parts of React Native's code also run on the web without any changes. To share code with React Native, React Native for Web imports the code it vendored from React Native. For example, [React Native for Web's implementation of `PanResponder`](https://github.com/necolas/react-native-web/blob/0e81c6ef2758d4ca9b2099b1d04a4f8c417f0f43/packages/react-native-web/src/exports/PanResponder/index.js) uses React Native's implementation:

```js
import PanResponder from '../../vendor/react-native/PanResponder';
export default PanResponder;
```

Finally, React Native for Web provides [a Babel plugin](https://github.com/necolas/react-native-web/tree/master/packages/babel-plugin-react-native-web) that rewrites all imports of `react-native` in your application code to import `react-native-web` instead. For example, `import { View } from 'react-native'` is rewritten to `import { View } from 'react-native-web'`.

React Native for Web's approach provides stability, as newly published patch versions of React Native -- which may have internal breaking changes despite keeping the public API unchanged -- will not affect the vendored code at all until the maintainer intentionally updates it.

### Overriding imports with Babel

Another solution is to write a Babel plugin that rewrites imports to files that need to be overridden. For example, let's say an out-of-tree platform needs to override React Native's `View.js` and that the overriding file is under `react-native-xx/View.xx.js`. Using a Babel plugin, one can rewrite all imports of React Native's `View.js` to instead import `react-native-xx/View.xx.js`. This Babel plugin simulates the current behavior of overriding files using Haste.

**Comment by ide** [comment]
Closing this out as part of 0.61. Thank you @cpojer for pushing this through internally.

**Comment by cpojer** [comment]
Yay we did it!
