### ISSUE TITLE
[Node 4] Prepare for Node 4

### ISSUE THREAD

**Issue by ide** [facebook/react-native#2545]
I believe the codebase is in good shape for Node 4.0. It's going to be much better when we can tell people just to get the latest version of Node without any of the io.js confusion.

Things that need to be done:
- [x] Update the documentation to tell people to install Node.js 4 or newer (#2546)
- [ ] Update the version check message in the packager (#2547)
- [x] Test with Node 4.0 RC. Some of the native modules like the WebSockets library may break since V8 is probably being upgraded from 4.4 to 4.5 but I expect we're OK since NAN is designed to protect against this. 
- [x] Upgrade the Travis CI tests to run against Node 4.0 (#2548)
- [x] Fix jest, which breaks when mocking bound functions (https://github.com/facebook/jest/issues/488)

cc @vjeux and @cpojer I think you will be excited

**Comment by cpojer** [comment]
* Does it have arrow functions like Chrome 45?
* Where can I find the RC?

**Comment by ide** [comment]
The RC is potentially getting cut later today. If the V8 4.5 upgrade lands in time, then I believe it includes with arrow functions (that aren't broken and behind a flag like in 3.x).

**Comment by cpojer** [comment]
They are now shipped natively in Chrome, and they are awesome.

**Comment by vjeux** [comment]
Me gusta

**Comment by ide** [comment]
Some good news: react-native installs fine with 4.0.0-rc.1. The packager, Chrome debugger, and React devtools all work with the UIExplorer. Almost all of the jest tests pass except this one:

```
 FAIL  Libraries/Utilities/__tests__/MessageQueue-test.js
SyntaxError: react-native/Libraries/Utilities/__tests__/MessageQueue-test.js: react-native/Libraries/Utilities/MessageQueue.js: react-native/Libraries/JavaScriptAppEngine/System/JSTimers/JSTimersExecution.js: Unexpected identifier
  at Function (native)
  at makeComponent (react-native/node_modules/jest-cli/src/lib/moduleMocker.js:157:15)
  at generateMock (react-native/node_modules/jest-cli/src/lib/moduleMocker.js:222:16)
  at Object.generateFromMetadata (react-native/node_modules/jest-cli/src/lib/moduleMocker.js:255:14)
```

**Comment by cpojer** [comment]
:+1: I have a reasonably important bug to fix for jest, I'll do that on Tuesday and tag 0.5.2.

**Comment by ide** [comment]
@vjeux could you find someone to look at #2548 (upgrade jest + travis), #2547 (add message to the packager), and #2546 (update docs) in that order? Once #2548 is in, we can also cherry-pick 7f65971761 over to 0.11-stable and ship Node 4.x support with 0.11 and not think about "io.js" any more.

**Comment by brentvatne** [comment]
@ide :heart_eyes:

**Comment by alinz** [comment]
:+1:

**Comment by cyprusglobe** [comment]
:+1:

**Comment by brunoksato** [comment]
+1

**Comment by chirag04** [comment]
Seems like everything is in place for node 4 now.
