### ISSUE TITLE
[0.13] Planning the next RC

### ISSUE THREAD

**Issue by ide** [facebook/react-native#3291]
@mkonicek is on 0.12 and we'll cut 0.13-rc soon after. Here are the main bugs that are holding up the release:

**General**:
- [x] ObjC tests are red - @javache looking into it, likely related to [this commit](https://github.com/facebook/react-native/commit/9e81dec5e44daf75f77a92635b75879dfa843990)
- [x] E2E tests are red - https://github.com/facebook/react-native/issues/3304, pinged @martinbigio

**iOS:**
- [ ] 3D touch breaks the gesture system due to an iOS 9.0 bug we should handle (@nicklockwood and @tadeuzagallo looking): https://github.com/facebook/react-native/issues/3082

**Android:**
- [x] ReadableNativeArray is missing, cannot compile: https://github.com/facebook/react-native/issues/3276, @mikearmstrong001 is looking into it
- [x] Reports that the Android UIExplorer has a redbox (need to verify on master but think I encountered this): https://github.com/facebook/react-native/issues/2983
- [x] Example apps crashing on Android (needs verification): https://github.com/facebook/react-native/issues/3289

**Infra:**
- [x] Packager has a syntax error due to not being transformed in some cases: https://github.com/facebook/react-native/issues/3262, @martinbigio says fix coming soon
- [ ] Test the basic workflow on Windows even if everything doesn't work like the Chrome debugger. After discussing with @mkonicek we're going to start with Windows support being a Community Responsibility and communicate that clearly. The best Windows support is going to come from people developing with RN master and using Windows on a daily basis so if someone wants to step up to the plate we can work with them on that. People are helping in #3348.
- [x] Rudimentary npm 3 support. We should get things to work even if the state of npm 3 isn't great. I believe there's a huge perf regression (may be fixed!) so most core devs are sticking with npm 2 but if it's not too hard to get npm 3 to be useable let's do that. #3317

It would be nice if we could include the AAR/JAR files with the npm distribution but it's not a launch blocker. Perhaps we could do that for 0.13 or 0.14-rc.

I'll take care of drafting the changelog.

**Comment by mkonicek** [comment]
@ide What is needed for npm 3 support? There's been one fix for npm 3: https://github.com/facebook/react-native/commit/daba14264c9f0d29c0327440df25d81c2f58316c?

**Comment by ide** [comment]
@mkonicek I haven't looked into npm 3 at all, but I'm hoping that it will be just one or two fixes for things to start working.

**Comment by Sinewyk** [comment]
Just saying that the npm3 perf regression (making it almost unuseable) has been fixed in npm https://github.com/npm/npm/releases/tag/v3.3.6 release. It's still a bit slower (by seconds) because it's doing a lot more work, but not by an order of magnitude like before (40-50x slower).

**Comment by mikearmstrong001** [comment]
#3082 @tadeuzagallo has added a comment, he is looking for repro steps as was unable to recreate

**Comment by ide** [comment]
Re #3082 you need an actual device with the pressure sensors to repro. Wasn't sure if they have 6s's yet. (If not -- here's something to write in a request ticket :)

**Comment by gre** [comment]
I'm sorry this might not be the right place but I don't know where else to ask,

When do you guys plan to depend on `react 0.14+` so we can write "universal" libraries that depends on `react` and works both on `react-dom` and `react-native` ?

**Comment by ide** [comment]
@gre it is planned but no ETA: https://github.com/facebook/react-native/issues/2985.

**Comment by gre** [comment]
Thanks :)

**Comment by ide** [comment]
I only have a Windows 8 VM and it's waiting in line for the Windows 10 upgrade. Opened https://github.com/facebook/react-native/issues/3348 so people interested in Windows support can help get it in for the next release.

**Comment by mkonicek** [comment]
I propose we cut the 0.13 branch now.

Checked with @tadeuzagallo, #3082 is going to take a while, we should cherry-pick it.
Likewise, can cherry-pick Windows-related fixes.

Want to cut the branch now when things are in a good state after the tests and packager fixes from end of last week. There's always a new release every two weeks and we can cherry-pick important fixes into 0.13.

**Comment by ide** [comment]
Sounds good. From #3348 it sounds like Windows might already work once we publish the 0.13-rc JAR and we can add other features like Chrome debugger support in 0.14 or 0.15.

**Comment by ide** [comment]
iOS UIExplorer and Android UIExplorer + Movies App (from source) work on 0.13-stable. So we need to build the Android libs, upload them, and then follow up with the people helping test initial Windows support and can release the RC.

**Comment by mkonicek** [comment]
Just released 0.13.0-rc to npm, CocoaPods and JCenter.

**Comment by ide** [comment]
Thanks @mkonicek!
