### ISSUE TITLE
[w3c] Web Props umbrella issue

### ISSUE THREAD

**Issue by necolas** [facebook/react-native#34424]
### Description

**Contingent on RFC feedback.** This is the umbrella issue for basic React DOM / Web props support on React Native components, as described in this proposal: "[RFC: Reduce fragmentation across platforms](https://github.com/react-native-community/discussions-and-proposals/pull/496)".

Each of the tasks listed below can be tackled with individual PRs that link back to this issue. Not every task has a known solution or implementation yet, so feel free to discuss implementation details in the comments. 

# Common props

These props should be supported by core components, i.e., `<Image>`, `<View>`, `<Text>`, `<TextInput>`, etc.

## Prop aliases

- [ ] Add [`aria-label`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) alias for [`accessibilityLabel`](https://reactnative.dev/docs/accessibility#accessibilitylabel).
- [ ] Add [`aria-modal`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal) alias for [`accessibilityViewIsModal`](https://reactnative.dev/docs/accessibility#accessibilityviewismodal-ios) (iOS).
- [ ] Add [`id`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id) alias for [`nativeID`](https://reactnative.dev/docs/view#nativeid).

Accessibility State

- [ ] Add [`aria-busy`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-busy) alias for [`accessibilityState.busy`](https://reactnative.dev/docs/accessibility#accessibilitystate).
- [ ] Add [`aria-checked`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-checked) alias for [`accessibilityState.checked`](https://reactnative.dev/docs/accessibility#accessibilitystate).
- [ ] Add [`aria-disabled`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-disabled) alias for [`accessibilityState.disabled`](https://reactnative.dev/docs/accessibility#accessibilitystate).
- [ ] Add [`aria-expanded`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded) alias for [`accessibilityState.expanded`](https://reactnative.dev/docs/accessibility#accessibilitystate).
- [ ] Add [`aria-selected`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-selected) alias for [`accessibilityState.selected`](https://reactnative.dev/docs/accessibility#accessibilitystate).

Accessibility Value

- [ ] Add [`aria-valuemax`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-valuemax) alias for [`accessibilityValue.max`](https://reactnative.dev/docs/accessibility#accessibilityvalue).
- [ ] Add [`aria-valuemin`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-valuemin) alias for [`accessibilityValue.min`](https://reactnative.dev/docs/accessibility#accessibilityvalue).
- [ ] Add [`aria-valuenow`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-valuenow) alias for [`accessibilityValue.now`](https://reactnative.dev/docs/accessibility#accessibilityvalue).
- [ ] Add [`aria-valuetext`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-valuetext) alias for [`accessibilityValue.text`](https://reactnative.dev/docs/accessibility#accessibilityvalue).

## Prop equivalents

- [ ] Add [`aria-hidden`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden).
  - [ ] Alias for [`importantforAccessibility='no-hide-descendants'`](https://reactnative.dev/docs/accessibility#importantforaccessibility-android) (Android).
  - [ ] Alias for [`accessibilityElementsHidden`](https://reactnative.dev/docs/accessibility#accessibilityelementshidden-ios) (iOS).
- [ ] Add [`aria-live`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions).
  - [ ] Alias for [`accessibilityLiveRegion`](https://reactnative.dev/docs/accessibility#accessibilityliveregion-android) (Android).
  - [ ] Map `aria-live='off'` to `accessibilityLiveRegion='none'`.
- [ ] Add [`role`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles).
  - [ ] Alias for [`accessibilityRole`](https://reactnative.dev/docs/view#accessibilityrole) but with full list of ARIA roles allowed.
  - [ ] Map `role='slider'` to `accessibilityRole='adjustable'`
  - [ ] Map `role='img'` to `accessibilityRole='image'`
  - [ ] Map `role='presentation'` to `accessibilityRole='none'`
  - [ ] Map `role='summary'` to `accessibilityRole='region'`
- [ ] Add [`tabIndex`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex).
  - [ ] Only support for `0` and `-1` values only.
  - [ ] Map `tabIndex={0}` to `focusable={true}` (Android)
  - [ ] Map `tabIndex={-1}` to `focusable={false}` (Android)

Example:

```jsx
<View
  aria-hidden={true}
  aria-busy={false}
  aria-label="Accessibility label"
  aria-valuetext="Middle"
  id="native-id"
  role="slider"
  tabIndex={0}
>

// same as

<View
  accessibilityElementsHidden={true}
  accessibilityLabel="Accessibility label"
  accessibilityRole="adjustable"
  accessibilityState={{ busy: false }}
  accessibilityValue={{ text: "Middle" }}
  focusable={true}
  importantforAccessibility='no-hide-descendants'
  nativeId="native-id"
>
```

# `<Image>` props

These props should be supported by `<Image>`.

- [ ] Add [`alt`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-alt).
  - [ ] Support alternative text support.
- [ ] Add [`crossOrigin`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-crossorigin).
   - [ ] Potentially map `crossOrigin='use-credentials'` to `source.headers['Access-Control-Allow-Credentials'] = true`.
- [ ] Add [`referrerPolicy`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-referrerpolicy).
   - [ ] Potentially map `referrerPolicy` to `source.headers['Referrer-Policy'] = referrerPolicy`.
- [ ] Add [`src`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-src).
   - [ ] Map `src` to `source.uri`.
- [ ] Add [`srcSet`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcSet).
   - [ ] Map `srcSet='path1 x1, path1 x2'` to `source=[{ uri: path1, scale: 1 },  { uri: path2, scale: 2 }]`.

Example mapping to `source`:

```js
const { crossOrigin, height, referrerPolicy, srcSet, width } = props;
const source = [];
const srcList = srcSet.split(', ');
srcList.forEach((src) => {
  const [uri, xscale] = src.split(' ');
  const scale = parseInt(xscale.split('x')[0], 10);
  const headers = {};
  if (crossOrigin === 'use-credentials') {
    headers['Access-Control-Allow-Credentials'] = true;
  }
  if (referrerPolicy != null) {
    headers['Referrer-Policy'] = referrerPolicy;
  }
  source.push({ headers, height, scale, uri, width });
});
```

Example:

```jsx
<Image
  alt="Alternative text"
  crossOrigin="use-credentials"
  height={300}
  referrerPolicy="origin"
  srcSet="https://image.png 1x, https://image2.png 2x"
  width={500}
>

// same as

<Image
  source={[
    {
      uri: "https://image.png",
      scale: 1,
      height: 300,
      headers: {
        'Access-Control-Allow-Credentials': true,
        'Referrer-Policy': 'origin'
      },
      width: 500
    }
    {
      uri: "https://image2.png",
      scale: 2,
      height: 300,
      headers: {
        'Access-Control-Allow-Credentials': true,
        'Referrer-Policy': 'origin'
      },
      width: 500
    }
  ]}
>
```

# `<TextInput>` props

These props should be supported by `<TextInput>`.

- [ ] Redefine `autoComplete`.
  * Unify values for Android ([`autoComplete`](https://reactnative.dev/docs/textinput#autocomplete-android)) and iOS ([`textContentType`](https://reactnative.dev/docs/textinput#textcontenttype-ios)) with Web ([`autoComplete`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)).
  * See code below for example mapping.
- [ ] Add [`enterKeyHint`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/enterkeyhint).
  - [ ] Map to equivalent [`returnKeyType`](https://reactnative.dev/docs/textinput#returnkeytype) values.
- [ ] Add [`inputMode`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode).
  - [ ] Map to equivalent [`keyboardType`](https://reactnative.dev/docs/textinput#keyboardtype) values.
  - [ ] Map `inputMode === 'decimal'` to `keyboardType = 'decimal-pad'`
  - [ ] Map `inputMode === 'email'` to `keyboardType = 'email-address'`
  - [ ] Map `inputMode === 'numeric'` to `keyboardType = 'numeric'`
  - [ ] Map `inputMode === 'search'` to `keyboardType = 'search'`
  - [ ] Map `inputMode === 'tel'`to `keyboardType = 'phone-pad'`
  - [ ] Map `inputMode === 'url'` to `keyboardType = 'url'`
- [ ] Add [`readOnly`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly).
  - [ ] Map `readOnly={false}` to `editable={true}`.
  - [ ] Map `readOnly={true}` to `editable={false}`.
- [ ] Add [`rows`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#attr-rows) (for `multiline={true}`).
  - [ ] Map `rows` to [`numberOfLines`](https://reactnative.dev/docs/textinput#numberoflines-android) (Android).

Example `autoComplete` mapping:

```js
// https://reactnative.dev/docs/textinput#autocomplete-android
const autoCompleteAndroid = {
 // web: android
  'address-line1': 'postal-address-region',
  'address-line2': 'postal-address-locality',
  bday: 'birthdate-full',
  'bday-day': 'birthdate-day',
  'bday-month': 'birthdate-month',
  'bday-year': 'birthdate-year',
  'cc-csc': 'cc-csc',
  'cc-exp': 'cc-exp',
  'cc-exp-month': 'cc-exp-month',
  'cc-exp-year': 'cc-exp-year',
  'cc-number': 'cc-number',
  country: 'postal-address-country',
  'current-password': 'password',
  email: 'email',
  name: 'name',
  'additional-name': 'name-middle',
  'family-name': 'name-family',
  'given-name': 'name-given',
  'honorific-prefix': 'namePrefix',
  'honorific-suffix': 'nameSuffix',
  'new-password': 'password-new',
  off: 'off',
  'one-time-code': 'sms-otp',
  'postal-code': 'postal-code',
  sex: 'gender',
  'street-address': 'street-address',
  tel: 'tel',
  'tel-country-code': 'tel-country-code',
  'tel-national': 'tel-national',
  username: 'username'
};

// https://reactnative.dev/docs/textinput#textcontenttype-ios
const autoCompleteIOS = {
 // web: ios
  'address-line1': 'streetAddressLine1',
  'address-line2': 'streetAddressLine2',
  'cc-number': 'creditCardNumber',
  'current-password': 'password',
  country: 'countryName',
  email: 'emailAddress',
  name: 'name',
  'additional-name': 'middleName',
  'family-name': 'familyName',
  'given-name': 'givenName',
  nickname: 'nickname',
  'honorific-prefix': 'name-prefix',
  'honorific-suffix': 'name-suffix',
  'new-password': 'newPassword',
  off: 'none',
  'one-time-code': 'oneTimeCode',
  organization: 'organizationName',
  'organization-title': 'jobTitle',
  'postal-code': 'postalCode',
  'street-address': 'fullStreetAddress',
  tel: 'telephoneNumber',
  url: 'URL',
  username: 'username'
};
```

Examples:

```jsx
<TextArea
  autoComplete="email"
  inputMode="email"
/>

// same as

<TextArea
  autoComplete="email"
  keyboardType="email-address"
  textContentType="emailAddress"
/>
```

```jsx
<TextArea
  multiline
  readOnly={true}
  rows={3}
/>

// same as

<TextArea
  editable={false}
  multiline
  numberOfLines={3}
/>
```

### Version

0.70

### Output of `npx react-native info`

.

### Steps to reproduce

.

### Snack, code example, screenshot, or link to a repository

[RFC: Reduce API fragmentation across platforms](https://github.com/react-native-community/discussions-and-proposals/pull/496)

**Comment by necolas** [comment]
See companion issue related to styles https://github.com/facebook/react-native/issues/34425

**Comment by TheTalonHughes** [comment]
I'd love to help out. This would be my first _real_ open source contribution. Is there anything I should be aware of in order to get started?

**Comment by gabrieldonadel** [comment]
@necolas I've just opened a PR adding the `readOnly` prop to the TextInput component (https://github.com/facebook/react-native/pull/34444), please let me know if this is what was expected or if it should be implemented using a different approach

**Comment by gabrieldonadel** [comment]
@necolas just FYI I've opened a PR tackling the `Add tabIndex` task here https://github.com/facebook/react-native/pull/34486

**Comment by necolas** [comment]
We have PRs either merged or open for every prop listed here except `aria-hidden`, `aria-live`, and `alt`. Big thanks to everyone who has contributed patches so far. This work is also going to indirectly help make React Native for Web better.

If you're still looking to contribute to this wider effort to bridge the gap between React Native and React DOM, we also have some styling tasks https://github.com/facebook/react-native/issues/34425

**Comment by nandorojo** [comment]
The following would also be great to add:

- `mask`
- `clip-path`
- `shape-outside`
- `filter`
- `mix-blend-mode`

**Comment by necolas** [comment]
> The following would also be great to add

Presumably you meant to post this on the styles umbrella issue?

There has to be an idea of how to implement these features though. Almost everything I've listed to date has already been bridged in RNWeb or a shim I wrote internally, so there's not a lot of new native work needed. Once we have added support for the easy props and styles, people can start looking into how to implement features that require new native code to be written.

**Comment by nandorojo** [comment]
> Presumably you meant to post this on the styles umbrella issue?

Ah, yep, posted on the wrong one.

> Once we have added support for the easy props and styles, people can start looking into how to implement features that require new native code to be written.

Sounds good.

**Comment by necolas** [comment]
I also want to set expectations: for at least the next 6 months, Meta is unlikely to be able to commit engineers to work on new native features to expand CSS support (with the exception of flexbox-related changes to Yoga). But if contributors who want these CSS features can develop and test them, we will help to integrate the code and give credit where it is due. Thanks!

**Comment by asherccohen** [comment]
Question: 
what about data- attributes?

some headless web UI libraries make huge use of them to attach some "state" to DOM, I'm worried that they are not transferrable.

Are those supported?

**Comment by necolas** [comment]
One more task has been added, which is to update the react-native-website docs to include all these new props once all the PRs have been merged.

**Comment by Viraj-10** [comment]
I think adding `aria-labelledby` aliases for `accessibilityLabelledBy` should be part of this Issue as well.

**Comment by necolas** [comment]
Good idea

**Comment by necolas** [comment]
I think `role` support is missing from `Text` (which appears to support `accessibilityRole`): https://github.com/facebook/react-native/blob/main/Libraries/Text/TextProps.js

[This logic](https://github.com/facebook/react-native/blob/main/Libraries/Components/View/View.js#L70) in `View` may need to be moved to a shared place so it can be used in `Text` too

**Comment by efoken** [comment]
I think `role="option"` is missing

**Comment by gabrieldonadel** [comment]
> I think `role` support is missing from `Text` (which appears to support `accessibilityRole`): https://github.com/facebook/react-native/blob/main/Libraries/Text/TextProps.js
> 
> [This logic](https://github.com/facebook/react-native/blob/main/Libraries/Components/View/View.js#L70) in `View` may need to be moved to a shared place so it can be used in `Text` too

Hi @necolas, just FYI I've opened a PR (https://github.com/facebook/react-native/pull/34976) a couple days ago tackling this

**Comment by necolas** [comment]
> I think role="option" is missing

Good spot. I'll add one more task to add `option`.

**Comment by gabrieldonadel** [comment]
> Good spot. I'll add one more task to add `option`.

@necolas what should we map the `role` option to? Should we add this new value natively on accessibilityRole as well?

**Comment by necolas** [comment]
It maps to nothing AFAICT, but needs to be included in the type for `role`

**Comment by gabrieldonadel** [comment]
> It maps to nothing AFAICT, but needs to be included in the type for `role`

Got it, I've just opened a PR for that https://github.com/facebook/react-native/pull/35137

**Comment by gabrieldonadel** [comment]
Hi @necolas, I saw that the `Update [react-native-website](https://github.com/facebook/react-native-website/) docs to include all these props` task was marked as completed. I believe some props are still missing tho, is someone from Meta going to work on this or is it still pending?

**Comment by necolas** [comment]
My mistake. Unchecked it again

**Comment by necolas** [comment]
All the props listed here have been implemented. Thanks so much to everyone who helped here, especially @gabrieldonadel for helping from start to end!

I'm going complete some updates to RNWeb so that it allows these props too.

And then I will probably create a "Part 2" issue with a few more props from the RFC. I'll also be updating the RFC with more details about the Event and Element APIs, which will likely form new umbrella issues.

**Comment by necolas** [comment]
If you have suggestions for more W3C props we could implement, please comment on "[RFC: Reduce fragmentation across platforms](https://github.com/react-native-community/discussions-and-proposals/pull/496)". I will start to publish updates to that RFC in the coming weeks. Thanks

**Comment by kmartinezmedia** [comment]
👋  Been closely following along this work and just want to thank all of you for pushing this effort forward!

Quick question: are there plans to align implementation/typescript values for accessibility props? I'm seeing react-native [uses boolean](https://github.com/facebook/react-native/blob/main/Libraries/Components/View/ViewAccessibility.d.ts#L58) while @types/react [uses Booleanish](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1653) which allows `boolean | 'true' | 'false'`

**Comment by retyui** [comment]
@necolas I noticed that `Touchable*` components doesn't have `accessibilityLabelledBy` & `aria-labelledby` props, is it  expected ?
