### ISSUE TITLE
[w3c] ☂️ Web Styles (Part 1) umbrella issue

### ISSUE THREAD

**Issue by necolas** [facebook/react-native#34425]
# Add support for Web styles to components

This is the umbrella issue for basic React DOM / Web style additions to React Native components, as described in this proposal: "[RFC: Reduce fragmentation across platforms](https://github.com/react-native-community/discussions-and-proposals/pull/496)".

Each of the tasks listed below can be tackled with individual PRs that link back to this issue. Not every task has a known solution or implementation yet, so feel free to discuss implementation details in the comments. Each new style property should take priority over any existing equivalents.

# Styles

## Basic extensions (All available in React Native 0.71)
- [x] [`aspectRatio`](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio) support for string values, i.e., `'16 / 9'`, to align with CSS. https://github.com/facebook/react-native/pull/34629
- [x] [`fontVariant`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant) support for space-separated string values, i.e., `'small-caps common-ligatures'`.
  - [x] https://github.com/facebook/react-native/pull/34641
  - [x] https://github.com/facebook/react-native/pull/36740 
- [x] [`fontWeight`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight) support for number values, i.e., `900`. https://github.com/facebook/react-native/pull/34598
- [x] [`transform`](https://developer.mozilla.org/en-US/docs/Web/CSS/transform) support for string values, i.e., `'scaleX(2) translateX(20px)'`. https://github.com/facebook/react-native/pull/34660#pullrequestreview-1104804653

Examples:

```jsx
<View
  style={{
    aspectRatio: '16 / 9',
    transform: 'scaleX(2) translateX(20px)'
  }}
>

<Text
  style={{
    fontVariant: 'small-caps common-ligatures',
    fontWeight: 900
  }}
>
```

### Available in React Native 0.71
- [x] `direction`.
- [x] Add [`objectFit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit). Partial equivalent to the `resizeMode` style and prop of `<Image>`. https://github.com/facebook/react-native/pull/34576
  - [x] Map `objectFit === 'contain'` to `resizeMode = 'contain'`.
  - [x] Map `objectFit === 'cover'` to `resizeMode = 'cover'`
  - [x] Map `objectFit === 'fill'` to `resizeMode = 'stretch'`
  - [x] Map `objectFit === 'scale-down'` to `resizeMode = 'contain'`
  - [ ] Support `objectFit` value of `'none'`.
- [x] Add [`pointerEvents`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events). Equivalent to the `pointerEvents` prop of `<View>`. https://github.com/facebook/react-native/pull/34586/
  - [x] Retain the React Native specific `box-none` and `box-only` values.
- [x] Add [`userSelect`](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select). Equivalent to using `selectable` prop on `<Text>`. https://github.com/facebook/react-native/pull/34575
- [x] Add [`verticalAlign`](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align). https://github.com/facebook/react-native/pull/34567
  - [x] Map `verticalAlign` to `textAlignVertical`.
  - [x] Map `verticalAlign === 'middle'` to `textAlignVertical = 'center'`;

### Available in React Native 0.72 
- Add CSS Logical Properties
  - [x] Logical Border Radius 
    - [x] https://github.com/facebook/react-native/pull/35342
    - [x] https://github.com/facebook/react-native/pull/35572
    * [x] `borderEndEndRadius` is equivalent to `borderBottomEndRadius`.
    * [x] `borderEndStartRadius` is equivalent to `borderBottomStartRadius`.
    * [x] `borderStartEndRadius` is equivalent to `borderTopEndRadius`.
    * [x] `borderStartStartRadius` is equivalent to `borderTopStartRadius`.
  * [x] Logical margin (Fabric-only)
    * [x] Map `marginInlineStart` to `marginStart`.
    - [x] Map `marginInlineEnd` to `marginEnd`.
    - [x] Map `marginBlockStart` to `marginTop`.
    - [x] Map `marginBlockEnd` to `marginBottom`.
    - [x] Map `marginBlock` to `marginVertical`.
    - [x] Map `marginInline` to `marginHorizontal`.
  - [x] Logical padding (Fabric-only)
    - [x] Map `paddingInlineStart` to `paddingStart`.
    - [x] Map `paddingInlineEnd` to `paddingEnd`.
    - [x] Map `paddingBlockStart` to `paddingTop`.
    - [x] Map `paddingBlockEnd` to `paddingBottom`.
    - [x] Map `paddingBlock` to `paddingVertical`.
    - [x] Map `paddingInline` to `paddingHorizontal`.
  - [x] Logical insets (Fabric-only) https://github.com/facebook/react-native/commit/9669c10afceef65626c82149210afc07d47df98b
    * [x] `inset` is equivalent to `top` & `bottom` & `right` & `left`.
    * [x] `insetBlock` is equivalent to `top` & `bottom`.
    * [x] `insetBlockEnd` is equivalent to `bottom`.
    * [x] `insetBlockStart` is equivalent to `top`.
    * [x] `insetInline` is equivalent to `right` & `left`.
    * [x] `insetInlineEnd` is equivalent to `right` or `left`.
    * [x] `insetInlineStart` is equivalent to `right` or `left`.
  - [x] https://github.com/facebook/react-native/pull/35999
  * [x] `borderBlockColor` is equivalent to `borderTopColor` & `borderBottomColor`.
  * [x] `borderBlockEndColor` is equivalent to `borderBottomColor`.
  * [x] `borderBlockStartColor` is equivalent to `borderTopColor`.

### Outstanding (version to be determined) 

- [ ] `borderStyle` value of `'none'`.
- [x] `transformOrigin` https://github.com/facebook/react-native/pull/37606
- [ ] Add CSS Logical Properties.
  - [x] https://github.com/facebook/react-native/pull/36046
  - [ ] https://github.com/facebook/react-native/pull/36242
  * [ ] `borderInlineColor` is equivalent to `borderEndColor` & `borderStartColor`.
  * [ ] `borderInlineEndColor` is equivalent to `borderEndColor`.
  * [ ] `borderInlineStartColor` is equivalent to `borderStartColor`.
  * [ ] `borderBlockStyle` is equivalent to `borderTopStyle` & `borderBottomStyle`.
  * [ ] `borderBlockEndStyle` is equivalent to `borderBottomStyle`.
  * [ ] `borderBlockStartStyle` is equivalent to `borderTopStyle`.
  * [ ] `borderInlineStyle` is equivalent to `borderEndStyle` & `borderStartStyle`.
  * [ ] `borderInlineEndStyle` is equivalent to `borderEndStyle`.
  * [ ] `borderInlineStartStyle` is equivalent to `borderStartStyle`.
  * [ ] `borderBlockWidth` is equivalent to `borderTopWidth` & `borderBottomWidth`.
  * [ ] `borderBlockEndWidth` is equivalent to `borderBottomWidth`.
  * [ ] `borderBlockStartWidth` is equivalent to `borderTopWidth`.
  * [ ] `borderInlineWidth` is equivalent to `borderEndWidth` & `borderStartWidth`.
  * [ ] `borderInlineEndWidth` is equivalent to `borderEndWidth`.
  * [ ] `borderInlineStartWidth` is equivalent to `borderStartWidth`.

Examples:

```jsx
<View
  style={{
    pointerEvents: 'none'
  }}
>

<Text
  style={{
    userSelect: 'none',
    verticalAlign: 'middle'
  }}
>

<Image
  style={{
    objectFit: 'cover'
  }}
>
```

### Available in React Native 0.71
- [x] Add expanded support for CSS Colors, e.g., `hsla()`. Potentially via [Colorjs.io](https://colorjs.io/). https://github.com/facebook/react-native/pull/34600
- [x] Add [`gap`](https://developer.mozilla.org/en-US/docs/Web/CSS/gap). https://github.com/facebook/yoga/pull/1116

```jsx
<View
  style={{
    boxShadow: '1px 1px 1px 1px #eee',
    backgroundColor: 'hsla(50,50,50,0.5)',
    backgroundImage: 'url(https://image.png)',
    pointerEvents: 'none',
    transform: 'scale(0.9)',
    width: '5rem'
  }}
>

<Text
  style={{
    textShadow: '1px 1px 1px #eee',
    userSelect: 'none',
    verticalAlign: 'middle'
  }}
>

<Image
  style={{
    objectFit: 'cover'
  }}
>
```

**Comment by necolas** [comment]
See companion issue related to props https://github.com/facebook/react-native/issues/34424

**Comment by nandorojo** [comment]
Would flex `gap` apply here, or does that fall out of scope since it's still missing in Yoga?

**Comment by necolas** [comment]
> Would flex `gap` apply here, or does that fall out of scope since it's still missing in Yoga?

Yes, that needs to be added to Yoga which is a whole other project.

> It would be great to add `objectPosition` for images too.

Done.

**Comment by meftunca** [comment]
please support for 'transform-origin' and 'display:grid'

**Comment by burakgormek** [comment]
Percentage values for `translate` would be good. We already have this on web.
Not sure if it's related to yoga, like flex `gap`.

`translateX(50%)`, `translateY(100%)`

**Comment by escaton** [comment]
> Yes, that needs to be added to Yoga which is a whole other project.

already [done](https://github.com/facebook/yoga/pull/1116), waiting for merge for 6 months

**Comment by gabrieldonadel** [comment]
> * Add expanded support for CSS Colors, e.g., `hsla()`. Potentially via [Colorjs.io](https://colorjs.io/).

Hi @necolas, which CSS Color Module Level do we wanna meet? React native already supports `rgb()`, `rgba()`, `#rgb`, `#rrggbb`, `#rgba`, `#rrggbbaa`, `hsl()`, `hsla()`, colors as int values (in RGB mode) and named colors, what else do we want to support? `hwb()`? `lab()`?

**Comment by necolas** [comment]
I added a new section for improving cross-platform compatibility of `Animated`.

It should be relatively easy to make Animated a separate package that works on web for React Native for Web. This would allow developers to have the same version of Animated running and avoid me needing to update Animated at arbitrary points in time, which is also tedious and error prone, as I have to check for new sources of crashes and copy-paste-edit dozens of files that use different module syntaxes and internal import paths to RN public APIs, like `StyleSheet`.

**Comment by necolas** [comment]
> already https://github.com/facebook/yoga/pull/1116, waiting for merge for 6 months

The RN team had planned to move to a new layout engine, but probably not anymore. So since there is an existing PR and it has a chance of being merged soon, I'll add `gap` too.

**Comment by gedeagas** [comment]
hi @necolas i am taking this.

```
Add [objectFit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit). Partial equivalent to the resizeMode style and prop of <Image>.
 Map objectFit === 'contain' to resizeMode = 'contain'.
 Map objectFit === 'cover' to resizeMode = 'cover'
 Map objectFit === 'fill' to resizeMode = 'stretch'
 Map objectFit === 'scale-down' to resizeMode = 'contain'```.

**Comment by efoken** [comment]
What about `marginBlock` for `marginVertical` and `marginInline` for `marginHorizontal`? And of course same for padding

**Comment by efoken** [comment]
Ah and also I wanted to note, that `lineHeight` currently only supports pixel values. What about adding support for values like `1.5` as a multiplier of the current font-size?

**Comment by necolas** [comment]
> What about adding support for values like 1.5 as a multiplier of the current font-size?

That would be great. Unfortunately, it would that be a breaking change since RN currently treats unitless line-height as pixels. So first we'd probably need something like a codemod to change all existing `lineHeight` values from e.g. `14` to `'14px'`, and then eventually re-introduce unitless value support as a multipler.

**Comment by sarulathadurai** [comment]
Hi @necolas I will be taking this 
`Add [boxShadow](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow).
 Add native support for single/multiple CSS box shadows.
 Cross-platform shadows to replace Android elevation style, and buggy iOS shadow* styles.`

**Comment by meftunca** [comment]
Please Add This Features List

1. Display Grid & Table
2. CSS Variable Support (For Global Theming)
3. transform-origin
4. position fixed&sticky

**Comment by nicoburns** [comment]
If flow layout is being added, then could grid layout also be considered? It's absolutely ideal for app layouts, and in many ways is a much simpler model than flexbox.

**Comment by efoken** [comment]
It would also be nice to add `inset`, a shorthand for setting `left`, `right`, `top` and `bottom`.

And also then maybe `StyleSheet.absoluteFill` and `StyleSheet.absoluteFillObject` can be deprecated?

**Comment by necolas** [comment]
I like this idea. `inset-inline` and `inset-block` would also be useful. I'll add a bunch more logical properties too once we have an idea of how to support them

**Comment by necolas** [comment]
@sarulathadurai are you still planning to work on box-shadow?

**Comment by sarulathadurai** [comment]
> @sarulathadurai are you still planning to work on box-shadow?

@necolas  apologies I can't take it up

**Comment by Marcoo09** [comment]
Hi @necolas, I'd like to help on this one if it's available
> * [ ]  Add [`backgroundImage`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image).

**Comment by necolas** [comment]
@Marcoo09 yes please, there is no existing PR. Since this isn't a feature that can simply be aliased to existing styles, you might want to first share how you plan to implement this feature, so we can run it past the RN team before you get started. Thanks

**Comment by gabrieldonadel** [comment]
> * Prevent crashes outside of native environments. This is mostly caused by TurboModule calls in `NativeAnimatedHelper`. We could either use a `*.web.js` mock or `Platform` guards. React Native for Web currently comments out the `flushQueue` function body to prevent crashes.

Hi @necolas, I was checking out `NativeAnimatedHelper` and it seems that we already have some `Platform` guards, do you mind elaborating a bit more on what needs to be updated?

https://github.com/facebook/react-native/blob/c63133202b015adc6cd94e77069586a619aca4a8/Libraries/Animated/NativeAnimatedHelper.js#L30-L33

**Comment by necolas** [comment]
The entire flushQueue function had to be commented out https://github.com/necolas/react-native-web/pull/2377/commits/ff72921b57951daf9c37939e9b4be108a1552718#diff-51312a304d660152aec0524a0aca4ca3667cbe604afe7f9c38a88bd8631e962d

**Comment by gabrieldonadel** [comment]
> The entire flushQueue function had to be commented out [necolas/react-native-web@ff72921#diff-51312a304d660152aec0524a0aca4ca3667cbe604afe7f9c38a88bd8631e962d](https://github.com/necolas/react-native-web/commit/ff72921b57951daf9c37939e9b4be108a1552718#diff-51312a304d660152aec0524a0aca4ca3667cbe604afe7f9c38a88bd8631e962d)

@necolas perhaps this was fixed by https://github.com/facebook/react-native/commit/5e863fc42c8a2b27f4a785766eb643de9a243b2d? I did some testing uncommenting that function and updating the code on `react-native-web` and it seems to work fine

**Comment by necolas** [comment]
I already did something similar to that patch https://github.com/necolas/react-native-web/commit/ff72921b57951daf9c37939e9b4be108a1552718#diff-6ef00d3c5589ec81f1dbc51139b50801209066f362c5d4d4788cd1bebcd0a13b

> I did some testing uncommenting that function and updating the code on react-native-web and it seems to work fine

That function calls turbomodules, which don't exist on web, so I'm curious what testing you did. And what code you updated...

**Comment by gabrieldonadel** [comment]
> I already did something similar to that patch [necolas/react-native-web@ff72921#diff-6ef00d3c5589ec81f1dbc51139b50801209066f362c5d4d4788cd1bebcd0a13b](https://github.com/necolas/react-native-web/commit/ff72921b57951daf9c37939e9b4be108a1552718#diff-6ef00d3c5589ec81f1dbc51139b50801209066f362c5d4d4788cd1bebcd0a13b)
> 
> > I did some testing uncommenting that function and updating the code on react-native-web and it seems to work fine
> 
> That function calls turbomodules, which don't exist on web, so I'm curious what testing you did. And what code you updated...

Actually you commented out the whole `flushQueue`, https://github.com/facebook/react-native/commit/5e863fc42c8a2b27f4a785766eb643de9a243b2d add some optional chaining to `NativeAnimatedModule` method calls and most importantly comments out `invariant(NativeAnimatedModule, 'Native animated module is not available');`



<details>
<summary>
Here is how my `flushQueue` function  looks like
</summary>

```js

 flushQueue: function (): void {
    // invariant(NativeAnimatedModule, 'Native animated module is not available');
    flushQueueTimeout = null;

    // Early returns before calling any APIs
    if (useSingleOpBatching && singleOpQueue.length === 0) {
      return;
    }
    if (!useSingleOpBatching && queue.length === 0) {
      return;
    }

    if (useSingleOpBatching) {
      // Set up event listener for callbacks if it's not set up
      if (
        !globalEventEmitterGetValueListener ||
        !globalEventEmitterAnimationFinishedListener
      ) {
        setupGlobalEventEmitterListeners();
      }
      // Single op batching doesn't use callback functions, instead we
      // use RCTDeviceEventEmitter. This reduces overhead of sending lots of
      // JSI functions across to native code; but also, TM infrastructure currently
      // does not support packing a function into native arrays.
      NativeAnimatedModule?.queueAndExecuteBatchedOperations?.(singleOpQueue);
      singleOpQueue.length = 0;
    } else {
      Platform.OS === 'android' &&
        NativeAnimatedModule?.startOperationBatch?.();
      for (let q = 0, l = queue.length; q < l; q++) {
        queue[q]();
      }
      queue.length = 0;
      Platform.OS === 'android' &&
        NativeAnimatedModule?.finishOperationBatch?.();
    }
  },
```
</details>

And I tested this through the [Lists example](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web-examples/pages/lists/index.js) as it uses an Animated FlatList, am I missing something @necolas ?

https://user-images.githubusercontent.com/11707729/199835759-c7d7fd4e-ac0f-4126-a04b-9c11ad4c2123.mov

**Comment by necolas** [comment]
OK cool, that looks like it should work then. My only concern is that at any moment an Animated patch could land that breaks web again

**Comment by gabrieldonadel** [comment]
> OK cool, that looks like it should work then. My only concern is that at any moment an Animated patch could land that breaks web again

Got it, but what would be the best way to prevent this from happening?  Would it be ok to add a `NativeAnimatedHelper.web.js` mock file? I don't see any other `web.js` files in the repo

**Comment by necolas** [comment]
There probably is no good way right now. I didn't even realize the previous patches to Animated broke it on web until I did the update a couple of months ago.

**Comment by gabrieldonadel** [comment]
> * Move `Animated` to a separate package within this monorepo and publish it to npm. Use the package to create the Animated components within React Native and React Native for Web.

Hi @necolas, I would like to help with this but I have a few questions:
 - How should we name this new package? `@react-native/animated`?
 - What should be the process for publishing this to npm? Should we open up a PR and then a Meta employee would publish it? 
 - How should we handle `react-native` imports inside this new package? e.g. currently we import some [utilities files ](https://github.com/facebook/react-native/blob/78aabd29ca935ef5a10c30c202c0305af4181922/Libraries/Animated/createAnimatedComponent.js#L14)

**Comment by necolas** [comment]
Let's ask @cortinico what he thinks, as the monorepo package setup is also being worked on here https://github.com/facebook/react-native/issues/34692. Nicola, we're interested in managing `Animated` out of its own package, and eventually publishing it to npm so react-native-web to depend on it. Do you have any initial concerns and suggestions?

**Comment by cortinico** [comment]
> Let's ask @cortinico what he thinks, as the monorepo package setup is also being worked on here https://github.com/facebook/react-native/issues/34692. Nicola, we're interested in managing `Animated` out of its own package, and eventually publishing it to npm so react-native-web to depend on it. Do you have any initial concerns and suggestions?
> 
> I'm open to moving this topic to another issue, as it's more about RNWeb compat than W3C compat. And there are similar reasons for wanting to package-ify `VirtualizedList` and `FlatList` too.

Sounds like a good idea, just note that all the packages apart from 'react-native' are manually bumped and published right now. We'll automate this in the future.

We probably want to call this `@react-native/animated` and place it inside packages/animated. cc @kelset

**Comment by necolas** [comment]
Thanks. I created a new umbrella issue to track/discuss these packages https://github.com/facebook/react-native/issues/35263

**Comment by kelset** [comment]
I think it's going to be hard to start splitting this right away - if you do, please ensure that the versioning they follow is on 0.<minor>.x semver, like react-native-gradle-plugin and other packs already do. (read more about this in the monorepo RFC)

**Comment by huzhanbo1996** [comment]
> 

Hi, are you still working on it? Maybe we can collaborate, since it looks like containing at least some works of adding CSS props, supporting on iOS and Android, image transformation. I'll try to make a Demo at first, if it's not done.

**Comment by nandorojo** [comment]
Is there interest in adding full support for `sizes` and `srcSet` to match the web `<img />` component? I have an implementation in [`solito/image`](https://github.com/nandorojo/solito/blob/next13/src/image/helpers.ts#L118-L250) using screen dimensions. Let me know if it'd be useful to move into core.

**Comment by dmahajan980** [comment]
Can adding support for `text-stroke` and `text-fill` be considered as well?

**Comment by necolas** [comment]
I added more properties to "CSS Logical Properties" that could be implemented in native as @NickGerleman did in #35342.

**Comment by gabrieldonadel** [comment]
> I added more properties to "CSS Logical Properties" that could be implemented in native as @NickGerleman did in #35342.

@necolas should all these `border....` properties be tackled in a single PR?

**Comment by necolas** [comment]
I don't think it matters how many PRs

**Comment by necolas** [comment]
I've removed some of the tasks that require brand new implementations in native. We'll close this umbrella issue once all the logical CSS aliases and textShadow PRs have been merged. Other style-related tasks will eventually be created from the RFC.

**Comment by gabrieldonadel** [comment]
@necolas should we implement `direction`, equivalent to `writingDirection` natively, or just map it to the existing prop using JS?

**Comment by necolas** [comment]
For some reason it's labelled as iOS-only despite being part of Yoga: https://reactnative.dev/docs/0.69/layout-props#direction

**Comment by XantreGodlike** [comment]
> Percentage values for `translate` would be good. We already have this on web. Not sure if it's related to yoga, like flex `gap`.
> 
> `translateX(50%)`, `translateY(100%)`

What the problem with support of percentage in translate props?

**Comment by gabrieldonadel** [comment]
@necolas FYI the following properties have been added via https://github.com/facebook/react-native/commit/9669c10afceef65626c82149210afc07d47df98b

> * `inset` is equivalent to `top` & `bottom` & `right` & `left`.
> * `insetBlock` is equivalent to `top` & `bottom`.
> * `insetBlockEnd` is equivalent to `bottom`.
> * `insetBlockStart` is equivalent to `top`.
> * `insetInline` is equivalent to `right` & `left`.
> * `insetInlineEnd` is equivalent to `right` or `left`.
> * `insetInlineStart` is equivalent to `right` or `left`.

**Comment by lunaleaps** [comment]
Question about some of these new style props -- are they all available on paper and fabric?

**Comment by necolas** [comment]
The "logical CSS" (e.g., marginInline, borderEndEndRadius) ones are only available on fabric IIRC (cc @NickGerleman)

**Comment by gabrieldonadel** [comment]
Actually, I ended up implementing logical border radius (e.g borderEndEndRadius) for paper as well on https://github.com/facebook/react-native/pull/35572

**Comment by lunaleaps** [comment]
For clarity for folks trying to use these props, could we add whether something is Fabric-only or any other details to prepare someone to use? Also, we can update what release they will be on. Just want to make sure we remove frustration in adoption! Or let me know if there's a better way

**Comment by gabrieldonadel** [comment]
Just FYI I'm currently working on adding support to the following props:
 
> * [ ]  `borderBlockColor` is equivalent to `borderTopColor` & `borderBottomColor`.
> * [ ]  `borderBlockEndColor` is equivalent to `borderBottomColor`.
> * [ ]  `borderBlockStartColor` is equivalent to `borderTopColor`.

I believe after this PR gets ready it will make things easier to add `Block`, `BlockEnd` and `BlockStart` props support for Paper as well. E.g. `marginBlock`

**Comment by gabrieldonadel** [comment]
And here is the PR adding support to the remaining border color props (https://github.com/facebook/react-native/pull/36046)

> * [ ]  `borderInlineColor`, equivalent to `borderEndColor` and `borderStartColor`.
> * [ ]  `borderInlineEndColor`, equivalent to `borderEndColor`.
> * [ ]  `borderInlineStartColor`, equivalent to `borderStartColor`.

**Comment by Pranav-yadav** [comment]
Hey @necolas !
Can I help w/ 👇 ? provided no one is already on it..
 > `borderBlockWidth` is equivalent to `borderTopWidth` & `borderBottomWidth`.
`borderBlockEndWidth` is equivalent to `borderBottomWidth`.
`borderBlockStartWidth` is equivalent to `borderTopWidth`.

**Comment by gabrieldonadel** [comment]
@Pranav-yadav might be better to wait for https://github.com/facebook/react-native/pull/36046/ as this renames all parameters of the CascadedRectangleEdges struct and will conflict

**Comment by Pranav-yadav** [comment]
> @Pranav-yadav might be better to wait for #36046 as this renames all parameters of the CascadedRectangleEdges struct and will conflict.
Edit: I guess you can also work based of that branch if you're comfortable with that

@gabrieldonadel Sure. Thanks for letting me know.

**Comment by necolas** [comment]
There's a bug in `Animated` when using the string syntax for transforms. The string syntax needs to be converted back to an array of objects for `AnimatedTransform` to work properly.

**Comment by Pranav-yadav** [comment]
> There's a bug in `Animated` when using the string syntax for transforms. The string syntax needs to be converted back to an array of objects for `AnimatedTransform` to work properly.

@necolas 
Should a similar approach as in https://github.com/necolas/react-native-web/commit/ed83baad20ddeb7a8c4acedbbbbca73bb12a1be7 fix this issue in react-native?

Also, haven't looked at it though seems like the new `AnimatedObject` #36935 also doesn't take care of this.

**Comment by nandorojo** [comment]
Could we add `position: sticky` here as well?

**Comment by necolas** [comment]
Closing as completed
