### ISSUE TITLE
☂️ npm packages for react-native-web

### ISSUE THREAD

**Issue by necolas** [facebook/react-native#35263]
### Description

These are spillover tasks from the W3C props & styles projects. The aim is to move user-space modules into their own packages within the monorepo. React Native for Web must currently copy-paste-edit these modules. Publishing these modules as npm packages will allow React Native and React Native for Web to depend on the same implementations, providing users of cross-platform React with a more reliable foundation (and making it easier for RNWeb to be maintained.)

Once again we're looking for the community's help! If you're interested in helping to reorganize the RN monorepo, you could contribute by helping to move these modules into packages with @cortinico's oversight. If you're interested in improving consistency between RN and RNWeb, you could contribute by helping to prepare those new packages for npm publication and consumption by RNWeb. We're also open to suggestions and feedback on how to proceed.

## Animated

- [x] Convert all files in the `Animated` directory to use ESModule imports/exports. https://github.com/facebook/react-native/pull/34539
- [x] Prevent crashes caused by use of TurboModules outside of native environments.
- [x] Patch `AnimatedStyle` for `Platform.OS === 'web'`. React Native for Web has a patch for this that can be upstreamed. https://github.com/facebook/react-native/pull/35198
- [ ] Move `Animated` to a separate package called `@react-native/animated` within `packages/animated`.
- [ ] Use the package to create the `Animated` components within React Native.
- [ ] Publish the package to npm with Flow types compiled out / to comments.
- [ ] Adopt `@react-native/animated` in React Native for Web.

## VirtualizedList

- [x] Move `VirtualizedList` and `VirtualizedSectionList` to a separate package called `@react-native/virtualized-lists` within `packages/virtualized-lists`. https://github.com/facebook/react-native/pull/35406
- [ ] Publish the package to npm with Flow types compiled out / to comments.
- [ ] Adopt `@react-native/virtualized-lists` in React Native for Web.

## FlatList

- [ ] Move `FlatList` and `SectionList` to a separate package called `@react-native/flat-lists` (name tbd?) within `packages/flat-lists`. https://github.com/facebook/react-native/pull/35423
- [ ] Publish the package to npm with Flow types compiled out / to comments.
- [ ] Adopt `@react-native/flat-lists` in React Native for Web.

**Comment by gabrieldonadel** [comment]
> * [ ]  Move `FlatList` and `SectionList` to a separate package called `@react-native/flat-lists` (name tbd?) within `packages/flat-lists`.

@necolas let me just double-check this for clarity, if I understand this correctly `@react-native/flat-lists` would have `@react-native/virtualized-lists` as a dependency, right?

Do we have plans on how to handle local changes in order to test these? AFAIK metro does not support symlinks

**Comment by necolas** [comment]
> If I understand this correctly @react-native/flat-lists would have @react-native/virtualized-lists as a dependency, right?

yeah I think so

> AFAIK metro does not support symlinks

does it not support Node.js resolution? we already have other packages broken out

**Comment by kelset** [comment]
@necolas you can read more about the symlink stuff here: https://github.com/facebook/react-native/issues/34692#issuecomment-1319190364 (once we figure it out for that effort, the learning will be useful here too)

**Comment by gabrieldonadel** [comment]
> * Move `VirtualizedList` and `VirtualizedSectionList` to a separate package called `@react-native/virtualized-lists` within `packages/virtualized-lists`.

@necolas should we also include the `RefreshControl` component in this package as it's used by `VirtualizedList`?

**Comment by Pranav-yadav** [comment]
@necolas / @kelset I've tried to move the `FlatList`s to `@react-native/flat-lists` package here [**DRAFT**] https://github.com/facebook/react-native/pull/35423
If any concerns[^1]; do let me know under the PR

PS: I'm following things discussed here as well as @gabrieldonadel 's PR :)

[^1]: I will wait for `@react-native/virtualized-lists` to merge and update the same in PR. Till then y'all can give feedback :)

**Comment by lunaleaps** [comment]
If any packages land before 0.72 is cut then we might need to create separate DT types for each separated package (only to be deprecated for 0.73)

**Comment by jacobp100** [comment]
Is there a goal here too to not have these packages's JS bundled in an RN app that's not using them? So if I'm not using FlatList, I won't have the JS bundled in my app?

**Comment by necolas** [comment]
Do we have an idea of when we will start publishing packages to npm with Flow types compiled out / to comments? It's currently not feasible for React Native for Web to depend on `@react-native/virtualized-lists` while the code on npm is invalid JS - https://www.npmjs.com/package/@react-native/virtualized-lists

**Comment by necolas** [comment]
I am still repeatedly answering issues from people who wonder why RN npm packages crash in web bundlers https://github.com/necolas/react-native-web/issues/2490

**Comment by hoxyq** [comment]
> Do we have an idea of when we will start publishing packages to npm with Flow types compiled out / to comments? It's currently not feasible for React Native for Web to depend on `@react-native/virtualized-lists` while the code on npm is invalid JS - https://www.npmjs.com/package/@react-native/virtualized-lists

I feel like this could be in scope of this project, maybe a separate task to support this across packages. Because this is not the part of monorepo project so far, and looks like `virtualized-lists` and `flat-lists` both should have it to be supported by `react-native-web`

**Comment by AndrewGable** [comment]
@necolas - Agreed, we do depend on React Native for our cross-platform product (`react-native-web` included). Please let us know if/how we (Expensify) can help move this project along. If there is anything we can do from implementation, design, or sponsor work; we are happy to help.

**Comment by necolas** [comment]
Thanks. Any of the incomplete tasks above are in need of attention. We still need to compile to JS before publishing too. I don't think there's a mechanism for automatic punishing yet, but manually publishing the packages once they've been created would be good enough for RNW to start the transition.

**Comment by Maxime-p** [comment]
Hi,
Small question. 
Why this issue isn't tag with a label "☂️ Umbrella"?
I am looking for a good first issue to contribute and I searched with the label and not all Umbrella issues appeared cause they are not tagged.
Sorry if I'm irrelevant.

**Comment by MCanhisares** [comment]
@necolas @cortinico do you guys still need help? I'm more than happy to take a look at some of these;  
`Move Animated to a separate package called @react-native/animated within packages/animated.` sounds fun

**Comment by DylanTet** [comment]
Started working on `Move Animated to a separate package called @react-native/animated within packages/animated.` @necolas @cortinico . Just trying to figure out which files need to be moved to the new folder.

**Comment by gabrieldonadel** [comment]
> Started working on `Move Animated to a separate package called @react-native/animated within packages/animated.` @necolas @cortinico . Just trying to figure out which files need to be moved to the new folder.

@DylanTet  I don't have the bandwidth to work on this right now but you can use my PR as a base for what needs to be changed https://github.com/facebook/react-native/pull/35467

**Comment by fnwk** [comment]
@necolas Hey, if no one is working on it, i can take care of "Move Animated to a separate package called @react-native/animated within packages/animated."

**Comment by sergioisidoro** [comment]
Also having issues specifically for `@react-native/assets` -- https://github.com/facebook/react-native/issues/36343

My use case is using react native + react native web to build cross platform ui elements.

**Comment by psnet** [comment]
so... as due to https://github.com/facebook/react-native/pull/50816#issuecomment-2818736259 it will never be done without huge breaking of all ecosystem of RN

so sad 🙅

**Comment by necolas** [comment]
We did it with VirtualizedList https://github.com/facebook/react-native/tree/main/packages/virtualized-lists

It usually shouldn't change anything for users of RN when parts are available as packages.

I'll close this issue since it's several years old and no longer in progress. Thanks for all the effort and progress made!
