### ISSUE TITLE
☂️ Improving `react-native-bot` 🤖

### ISSUE THREAD

**Issue by kelset** [facebook/react-native#35591]
## What this is about

This umbrella issue wants to expand on some work that was started via this PR https://github.com/facebook/react-native/pull/35500 by @SlyCaptainFlint and on which we followed up with some conversations in the Discord with @cortinico.

The core goal is to improve the overall experience for both users and maintainers when interacting with the react-native repository, by leveraging "more and better" automations that are possible (mostly handled via the `react-native-bot` currently).

### Ideas

In no particular order:

- [x] Run the stale bot more often (2/3 times a day) as it reaches the API request capacity due to the amount of issues we have
- [x] Stale the issues labeled with 'Needs: Author Feedback' more often (like 30 days or so).
- [x] Reword some of the [bot responses](https://github.com/facebook/react-native/blob/main/.github/workflows/on-issue-labeled.yml) by taking inspiration from
  - [x] https://stackoverflow.com/help/minimal-reproducible-example
  - [x] https://stackoverflow.com/help/how-to-ask
- [ ] Find a way for the bot to verify if the repro steps are actually valid and not, ex. just a screenshot
  - Tool that does something of this sort: https://github.com/arcanis/sherlock
- [x] Have the bot verify if a reproducer has been provided (link to either a snack or a repo under the user profile). i.e. Auto-detect the Needs Repro:
  - Similar to this: https://github.com/software-mansion/react-native-screens/issues/1816#issuecomment-1628935746
  - Or here: https://github.com/react-navigation/react-navigation/issues/11026#issuecomment-1322684290 
- [ ] Have the bot enforce more the template
  - ex. if someone labels something posts a bug by then they copy-paste dump an entire stacktrace, removing all the sections and formatting, it should close it or warn then close after a few days
- [x] Update the template to use `render: shell` to properly render stacktraces and `react-native config`
- [ ] Update the template to request a green run of `react-native doctor`
- [ ] Inspect of the environment/versions automatically like: https://github.com/react-navigation/react-navigation/issues/11028#issuecomment-1326702379 

*We'll be using this issue to refine the list above, adding, removing, and editing points as needed, to then lead to PRs to apply them in the future.*

**Comment by cortinico** [comment]
On top of what you suggested @kelset:

1. Auto-detect the Needs Repro like here: https://github.com/react-navigation/react-navigation/issues/11026#issuecomment-1322684290 
2. Inspect of the environment/versions automatically like:
https://github.com/react-navigation/react-navigation/issues/11028#issuecomment-1326702379 

For context if folks want to start moving the logic from `react-native-bot` to Github Actions. The code of the old bot is inside: https://github.com/cortinico/react-native-bot
So once a feature has been ported to GH Actions, it should be removed/commented from that codebase so the two bots don't conflict each other

**Comment by kelset** [comment]
@cortinico what do you think, do we still need this open?

**Comment by cortinico** [comment]
@kelset I think yes, I've also added more items to the list for ideas we collected.

**Comment by cortinico** [comment]
@kacperkapusciak awesome, are you up for integrating it inside `react-native`?

**Comment by kacperkapusciak** [comment]
@cortinico okay, I can spend some time on it

Would you like me to integrate our `swmansion-bot/needs-repro` action that we use as is (you can adjust the labels and the bot's response) or make it inline as you have here: https://github.com/facebook/react-native/blob/main/.github/workflows/close_pr.yml (full control of the code on your side).
 
 Which one do you prefer?

**Comment by cortinico** [comment]
> or make it inline as you have here: [`main`/.github/workflows/close_pr.yml](https://github.com/facebook/react-native/blob/main/.github/workflows/close_pr.yml?rgh-link-date=2023-07-12T10%3A24%3A52Z) (full control of the code on your side).

I think the best would be to have the logic inside https://github.com/facebook/react-native/tree/main/.github/workflow-scripts and copied over (for security reasons)

**Comment by kacperkapusciak** [comment]
@cortinico seems reasonable, I'll submit a PR in the following days

**Comment by kacperkapusciak** [comment]
@cortinico initial version is ready to check and open for discussion https://github.com/facebook/react-native/pull/38338

**Comment by samitha9125** [comment]
@kelset I can help with `Inspect of the environment/versions automatically`. Basically, what I thought was to update the Issue template requesting versions of main packages that RN depends on. If they are not available, github bot will comment, just like the example provided in the initial description. Sounds good?

**Comment by samitha9125** [comment]
PR is ready to review. Feedbacks are welcome :) #40655

**Comment by cortinico** [comment]
Closing as most of the issues here have been implemented 👍 We'll come up with another round of improvements whenever we feel there is the need for
