### ISSUE TITLE
☂️ Help us Kotlin-ify React Native tests

### ISSUE THREAD

**Issue by mdvacca** [facebook/react-native#37708]
### Description

Hey all 👋
We're looking for some community support to help us prepare the codebase of React Native Android to be ready to migrate to Kotlin. In this first stage we are looking for help to migrate tests to Kotlin

### How to migrate a test

If you wish to convert one of the tests you should:

* Verify that the test is not claimed yet.
* Comment here that you claim a test.
* Start working on adding Kotlin support for the test.
    * Make sure your environment is set up correctly (see below) 
    * Use this PR as inspiration: [**Convert RootViewTest to Kotlin** - #37227](https://github.com/facebook/react-native/pull/37227) 
    * Make sure the test run correctly (see below).
    * Your Kotlin code should be formatted with ktfmt (see below).
* Send the PR for review. Ping @cortinico and @mdvacca for a review.

### Setting up your environment

Make sure your environment is set correctly, specifically you need to:
1. [Fork react-native](https://github.com/facebook/react-native/fork)
2. Clone react-native locally
3. Run `yarn` inside your local fork ([installation instruction for yarn are here](https://classic.yarnpkg.com/lang/en/docs/install/#mac-stable))
4. Make sure you have Java 11 installed and the Android SDK configured (you can [follow our official guide here](https://reactnative.dev/docs/environment-setup))

### Running your tests

You can run your tests either by using the Android Studio/IntelliJ UI or by invoking the following command in your React Native fork:

```
./gradlew :packages:react-native:ReactAndroid:test
```

### Code formatting

Please use [KtFmt](https://facebook.github.io/ktfmt/) to format Kotlin tests.
You can use the web UI to reformat directly from the browser:
https://facebook.github.io/ktfmt/

### List of tests to migrate

- [x] [common/logging/FakeLoggingDelegate.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/common/logging/FakeLoggingDelegate.java) assigned to @MohamedRejeb
- [x] [react/CompositeReactPackageTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/CompositeReactPackageTest.java) assigned to @MohamedRejeb
- [x] [react/animated/NativeAnimatedInterpolationTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/animated/NativeAnimatedInterpolationTest.java) assigned to @fabioh8010 
- [x] [react/animated/NativeAnimatedNodeTraversalTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/animated/NativeAnimatedNodeTraversalTest.java) - Assigned to @ankit-tailor
- [x] [react/bridge/FallbackJSBundleLoaderTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/FallbackJSBundleLoaderTest.java) Assigned to @fabioh8010
- [x] [react/bridge/InstanceHandleHelper.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/InstanceHandleHelper.java) assigned to @arslandogar
- [x] [react/bridge/JavaOnlyArrayTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/JavaOnlyArrayTest.java) assigned to @rozkminiacz 
- [x] [react/bridge/JavaScriptModuleRegistryTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/JavaScriptModuleRegistryTest.java) assigned to @stanwolverine
- [x] [react/bridge/ReactTestHelper.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/ReactTestHelper.java) assigned to @abdennour-jebbar-nw
- [x] [react/bridge/BaseJavaModuleTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/BaseJavaModuleTest.java) assigned to @abdennour-jebbar-nw
- [x]  [react/bridge/interop/FakeRCTEventEmitter.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/interop/FakeRCTEventEmitter.java) assigned to @dcangulo
- [x] [react/bridge/interop/InteropModuleRegistryTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/interop/InteropModuleRegistryTest.java) assigned to @dcangulo
- [x] [react/devsupport/MultipartStreamReaderTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/devsupport/MultipartStreamReaderTest.java) assigned to @brunohensel
- [x] [react/devsupport/StackTraceHelperTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/devsupport/StackTraceHelperTest.java) assigned to @koko57 
- [x] [react/fabric/events/TouchEventDispatchTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/fabric/events/TouchEventDispatchTest.java) assigned to @MohamedRejeb 
- [x] [react/fabric/interop/FakeEventDispatcher.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/fabric/interop/FakeEventDispatcher.java) assigned to @tarunrajput
- [x] [react/fabric/interop/InteropEventEmitterTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/fabric/interop/InteropEventEmitterTest.java) assigned to @stanwolverine
- [x] [react/modules/blob/BlobModuleTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/blob/BlobModuleTest.java) assigned to @mateusz1913  
- [x] [react/modules/camera/ImageStoreManagerTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/camera/ImageStoreManagerTest.java) assigned to @megatunger
- [x] [react/modules/clipboard/ClipboardModuleTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/clipboard/ClipboardModuleTest.java) assigned to @hurali97
- [x] [react/modules/deviceinfo/DeviceInfoModuleTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/deviceinfo/DeviceInfoModuleTest.java) assigned to @okwasniewski
- [x] [react/modules/dialog/DialogModuleTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/dialog/DialogModuleTest.java) assigned to @fathonyfath
- [x] [react/modules/network/HeaderUtilTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/network/HeaderUtilTest.java) assigned to @TheMissouri
- [x] [react/modules/network/ReactCookieJarContainerTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/network/ReactCookieJarContainerTest.java) assigned to @pk-218
- [x] [react/modules/network/ProgressiveStringDecoderTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/network/ProgressiveStringDecoderTest.java) assigned to @RyanGst
- [x] [react/modules/share/ShareModuleTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/share/ShareModuleTest.java) assigned to @siddarthkay
- [x] [react/packagerconnection/JSPackagerClientTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/packagerconnection/JSPackagerClientTest.java) assigned to @brunohensel
- [x] [react/uimanager/UIManagerModuleConstantsHelperTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/uimanager/UIManagerModuleConstantsHelperTest.java) assigned to @ryanlntn
- [x] [react/uimanager/layoutanimation/InterpolatorTypeTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/uimanager/layoutanimation/InterpolatorTypeTest.java) assigned to @Janjs
- [x] [react/util/JSStackTraceTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/util/JSStackTraceTest.java) assigned to @aymane-missouri-nw

**Comment by cortinico** [comment]
> Hey @cortinico, Please assign me [react/animated/NativeAnimatedNodeTraversalTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/animated/NativeAnimatedNodeTraversalTest.java?rgh-link-date=2023-06-06T08%3A55%3A09Z).

Done 👍

**Comment by okwasniewski** [comment]
Hey @cortinico, you can assign me to [react/modules/deviceinfo/DeviceInfoModuleTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/deviceinfo/DeviceInfoModuleTest.java)

**Comment by hurali97** [comment]
Hey @cortinico , can you assign me [react/modules/clipboard/ClipboardModuleTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/clipboard/ClipboardModuleTest.java) ?

**Comment by MohamedRejeb** [comment]
Hey @cortinico , assign me [react/fabric/events/TouchEventDispatchTest.java](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/fabric/events/TouchEventDispatchTest.java)

**Comment by fabioh8010** [comment]
Hey @cortinico, can you assign me to this one [react/animated/NativeAnimatedInterpolationTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/animated/NativeAnimatedInterpolationTest.java)?

**Comment by TheMissouri** [comment]
Hey @cortinico , can you assign me react/util/JSStackTraceTest.java ?

**Comment by aymane-missouri-nw** [comment]
hey @cortinico , can you assign me to this one [react/util/JSStackTraceTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/util/JSStackTraceTest.java)

**Comment by rozkminiacz** [comment]
Hi @cortinico , you can assign me to
[react/bridge/JavaOnlyArrayTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/JavaOnlyArrayTest.java)
 [react/bridge/JavaScriptModuleRegistryTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/JavaScriptModuleRegistryTest.java)

**Comment by TheMissouri** [comment]
Hey @cortinico , can you assign me to this one [react/modules/network/HeaderUtilTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/network/HeaderUtilTest.java)

**Comment by siddarthkay** [comment]
Hey @cortinico , I'd like to take this one https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/share/ShareModuleTest.java
please assign it to me

**Comment by mateusz1913** [comment]
Hey @cortinico, assign me to [react/modules/blob/BlobModuleTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/blob/BlobModuleTest.java)

**Comment by tarunrajput** [comment]
Hi @cortinico, I'd like to work on this one : [react/fabric/interop/FakeEventDispatcher.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/fabric/interop/FakeEventDispatcher.java)

**Comment by megatunger** [comment]
Hi @cortinico, can you assign this one to me? [react/modules/camera/ImageStoreManagerTest.java](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/camera/ImageStoreManagerTest.java)

**Comment by cortinico** [comment]
Awesome stuff, I've assigned all the tasks that got claimed so far. Folks that got a test class assigned, can start working on it.

**Comment by fathonyfath** [comment]
hey @cortinico , could you assign me this one [react/modules/dialog/DialogModuleTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/dialog/DialogModuleTest.java)

I'll try to help as much as possible :)

**Comment by koko57** [comment]
Hi @cortinico! Could you please assign [react/devsupport/StackTraceHelperTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/devsupport/StackTraceHelperTest.java) to me? 🙂

**Comment by abdennour-jebbar-nw** [comment]
Hello @cortinico! please assign [react/bridge/ReactTestHelper.java](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/ReactTestHelper.java) to me

**Comment by ryanlntn** [comment]
Hi @cortinico! Please assign [react/uimanager/UIManagerModuleConstantsHelperTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/uimanager/UIManagerModuleConstantsHelperTest.java) to me.

**Comment by mdvacca** [comment]
Thanks everyone! I've assigned all the tasks that got claimed so far. Folks that got a test class assigned, can start working on it.

**Comment by MohamedRejeb** [comment]
Hey @cortinico assign me the remaining one please.
[common/logging/FakeLoggingDelegate.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/common/logging/FakeLoggingDelegate.java)
 [react/CompositeReactPackageTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/CompositeReactPackageTest.java)
[react/bridge/FallbackJSBundleLoaderTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/FallbackJSBundleLoaderTest.java)
[react/bridge/interop/FakeRCTEventEmitter.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/interop/FakeRCTEventEmitter.java)
 [react/bridge/interop/InteropModuleRegistryTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/interop/InteropModuleRegistryTest.java)

**Comment by cortinico** [comment]
> Hey @cortinico assign me the remaining ones please.

Hey @MohamedRejeb, to give everyone a chance to contribute, we're not allowing more than 2 files per person. I've assigned you `FakeLoggingDelegate.java` and `CompositeReactPackageTest.java`

**Comment by dcangulo** [comment]
@cortinico Can I get https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/interop/FakeRCTEventEmitter.java?

**Comment by dcangulo** [comment]
@cortinico Since you allow at most 2 files and no one else commenting, can I get [react/bridge/interop/InteropModuleRegistryTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/interop/InteropModuleRegistryTest.java)?

**Comment by mdvacca** [comment]
Thanks everyone! all the files have been assigned!

**Comment by amrfarid140** [comment]
Hey! happy to convert https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/timing/TimingModuleTest.java

**Comment by stanwolverine** [comment]
@mdvacca Any pending test for me?

**Comment by mdvacca** [comment]
@stanwolverine, would you like to take: 

[react/animated/NativeAnimatedNodeTraversalTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/animated/NativeAnimatedNodeTraversalTest.java)

[react/fabric/interop/InteropEventEmitterTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/fabric/interop/InteropEventEmitterTest.java)

**Comment by ankit-tailor** [comment]
Hey @mdvacca, `NativeAnimatedNodeTraversalTest` is already [migrated](https://github.com/facebook/react-native/pull/37960).

**Comment by mdvacca** [comment]
@rozkminiacz, @jasokolowska, are you working on: 

- [react/bridge/JavaScriptModuleRegistryTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/JavaScriptModuleRegistryTest.java) assigned to 

- [react/fabric/interop/InteropEventEmitterTest.java](https://github.com/facebook/react-native/tree/main/packages/react-native/ReactAndroid/src/test/java/com/facebook/react/fabric/interop/InteropEventEmitterTest.java)

otherwise, we can reassign them to @stanwolverine

**Comment by stanwolverine** [comment]
@mdvacca thanks, I will start working

**Comment by rupam-seal** [comment]
@mdvacca, do you have any test for me?

**Comment by cortinico** [comment]
> @mdvacca, do you have any test for me?

Currently all the tests are assigned. If @stanwolverine doesn't send both PRs by the end of tomorrow, we can assign those tests to you @rupam-seal

**Comment by rupam-seal** [comment]
Ok Thank you!🫡

**Comment by stanwolverine** [comment]
Hey @cortinico and @rupam-seal , After solving many issues while setting up react-native on my local machine, I was able to finish both tests. I will send both PRs before the end of tomorrow.

**Comment by mdvacca** [comment]
Thanks everyone for contributing to migrate React Native Android tests to Kotlin

Since all the tests on the list were migrated, I'm closing this issue!
