### ISSUE TITLE
☂️ Help us migrate Android tests to AssertJ

### ISSUE THREAD

**Issue by cortinico** [facebook/react-native#45596]
Hey all 👋
We'd like to use the community some support to help us migrate our to AssertJ (https://assertj.github.io/doc/#assertj-core).

We prepared a list of files that should be migrated from JUnit's Asserts (i.e. `import org.junit.Assert...`) from AssertJ (i.e. `import org.assertj...`).

AssertJ is a more powerful assertion library which makes it immediately clear where the test failure is.

### How to work

The recommended number of files to **migrate together is 3-5**

If you wish to migrate some of the files you should:
* Verify that the files is not claimed yet.
* Comment here which files you want to claim.
* Start working on the task. Testing instructions are below.
* Send the PR for review. Ping @cortinico for a review.
* If you’re not completing the task within a week, we’ll release it for the next contributor.

You can't claim more than 5 files at a time.

### How to migrate a test

You can see an **example of a test migration** in this commit:
https://github.com/facebook/react-native/commit/91ecd7eb5330f5d725f5587744713064d614a6b3

You can read the guide here:
https://assertj.github.io/doc/#assertj-core-assertions-guide
on how to migrate a test from JUnit's assertion to AssertJ

### List of files to migrate

- [x] `packages/gradle-plugin/shared/src/test/kotlin/com/facebook/react/utils/TaskUtilsTest.kt` assigned to @migueldaipre
- [x] `packages/gradle-plugin/shared/src/test/kotlin/com/facebook/react/utils/JsonUtilsTest.kt` assigned to @migueldaipre
- [x] `packages/gradle-plugin/shared/src/test/kotlin/com/facebook/react/utils/OsTest.kt` assigned to @migueldaipre
- [x] `packages/gradle-plugin/shared/src/test/kotlin/com/facebook/react/utils/KotlinStdlibCompatUtilsTest.kt` assigned to @kachmashk
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/model/ModelAutolinkingDependenciesJsonTest.kt` assigned to @kachmashk
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/utils/PathUtilsTest.kt` assigned to @kachmashk
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/utils/DependencyUtilsTest.kt` assigned to @kachmashk
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/utils/ProjectUtilsTest.kt` assigned to @kachmashk
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/utils/FileUtilsTest.kt` assigned to @henriquecicero
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/utils/NdkConfiguratorUtilsTest.kt` assigned to @henriquecicero
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/utils/AgpConfiguratorUtilsTest.kt` assigned to @henriquecicero
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/utils/BackwardCompatUtilsTest.kt` assigned to @gustavoabel
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/BundleHermesCTaskTest.kt` assigned to @omer-ayhan 
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/GenerateCodegenSchemaTaskTest.kt` assigned to @omer-ayhan
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/internal/PrepareGlogTaskTest.kt` assigned to @migueldaipre 
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/internal/BuildCodegenCLITaskTest.kt` assigned to @migueldaipre 
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/internal/PrepareBoostTaskTest.kt` assigned to @bionanek
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/internal/PrepareJSCTaskTest.kt` assigned to @BogiKay
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/internal/PreparePrefabHeadersTaskTest.kt` assigned to @omer-ayhan
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/GeneratePackageListTaskTest.kt` assigned to @omerayhan-shft
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/GenerateCodegenArtifactsTaskTest.kt` assigned to @Tony-MK
- [x] `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/ReactExtensionTest.kt` assigned to @barbarosaffan
- [x] `packages/react-native/ReactAndroid/src/test/java/com/facebook/react/uimanager/UIManagerModuleConstantsHelperTest.kt` assigned to @yakupozbaydar
- [x] `packages/react-native/ReactAndroid/src/test/java/com/facebook/react/ReactActivityDelegateTest.kt` assigned to @gustavoabel
- [x] `packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/clipboard/ClipboardModuleTest.kt` assigned to @retyui
- [x] `packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/share/ShareModuleTest.kt` assigned to @migueldaipre
- [x] `packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/blob/BlobModuleTest.kt` assigned to @bufgix
- [x] `packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/model/ReactModuleInfoTest.kt` assigned to @jaworek
- [x] `packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/dialog/DialogModuleTest.kt` assigned to @jaworek
- [x] `packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/network/HeaderUtilTest.kt` assigned to @gustavoabel
- [x] `packages/react-native/ReactAndroid/src/test/java/com/facebook/react/fabric/FabricUIManagerTest.kt` assigned to @jaworek
- [x] `packages/react-native/ReactAndroid/src/test/java/com/facebook/react/fabric/internal/interop/InteropUiBlockListenerTest.kt` assigned to @Skipperlla
- [x] `packages/react-native/ReactAndroid/src/test/java/com/facebook/react/defaults/DefaultNewArchitectureEntryPointTest.kt` assigned to @migueldaipre
- [x] `packages/react-native/ReactAndroid/src/test/java/com/facebook/react/internal/interop/InteropEventEmitterTest.kt` assigned to @migueldaipre
- [x] `packages/react-native/ReactAndroid/src/test/java/com/facebook/react/bridge/interop/InteropModuleRegistryTest.kt` assigned to @migueldaipre

## How to test

Make sure the test is running correctly after you migrated it.

You can test it as follows:
1. For tests inside `packages/react-native/` with the command:
```
./gradlew test
```

2. For tests inside `packages/gradle-plugin/` with the command:
```
./gradlew -p packages/gradle-plugin test
```

**Comment by migueldaipre** [comment]
Hey @cortinico , 

Please assign me `TaskUtilsTest.kt`, `JsonUtilsTest.kt` and `OsTest.kt`

**Comment by kachmashk** [comment]
Hey!
I'll be taking next 4 after @migueldaipre `KotlinStdlibCompatUtilsTest.kt`, `ModelAutolinkingDependenciesJsonTest.kt`, `PathUtilsTest.kt` & `DependencyUtilsTest.kt`.

**Comment by cortinico** [comment]
@migueldaipre @kachmashk done.
Also @kachmashk I've assigned only 5 to leave some for others to do as well, you can claim more once you're done with yours.

**Comment by kachmashk** [comment]
Sure thing @cortinico, will change my comment one last time then to remove the sixth one.

**Comment by retyui** [comment]
Please assign me  `ClipboardModuleTest.kt`

**Comment by henriquecicero** [comment]
Hey, @cortinico.

I would like to take `FileUtilsTest.kt`, `NdkConfiguratorUtilsTest.kt` and `AgpConfiguratorUtilsTest.kt`, please.

**Comment by bionanek** [comment]
hey there!  I can take care of `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/internal/PrepareBoostTaskTest.kt`

**Comment by bufgix** [comment]
Hey 👋 i would like to take `packages/react-native/ReactAndroid/src/test/java/com/facebook/react/modules/blob/BlobModuleTest.kt`. Thank you

**Comment by gustavoabel** [comment]
Hey @cortinico, please assign me ```BackwardCompatUtilsTest.kt```

**Comment by migueldaipre** [comment]
Hey @cortinico. I'd like to migrate 3 more files.

- `DefaultNewArchitectureEntryPointTest.kt`
- `InteropEventEmitterTest.kt`
- `InteropModuleRegistryTest.kt`

**Comment by gustavoabel** [comment]
Hey @cortinico, I would like to migrate these too:

- ```HeaderUtilTest.kt```
- ```ReactActivityDelegateTest.kt```

**Comment by Skipperlla** [comment]
Hey 👋 i would like to take `packages/react-native/ReactAndroid/src/test/java/com/facebook/react/fabric/internal/interop/InteropUiBlockListenerTest.kt`. Thank you

**Comment by omerayhan-shft** [comment]
Hey 👋 i would like to take `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/GeneratePackageListTaskTest.kt`. Thank you

**Comment by omerayhan-shft** [comment]
Hey 👋 i would like to take `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/internal/PreparePrefabHeadersTaskTest.kt`. Thank you

**Comment by Tony-MK** [comment]
Hey @cortinico , can assign me for the following:

```packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/GeneratePackageListTaskTest.kt```

```
packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/GenerateCodegenArtifactsTaskTest.kt
```

Thanks

**Comment by omer-ayhan** [comment]
Hey @cortinico 👋 i would like to take packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/internal/PreparePrefabHeadersTaskTest.kt. Thank you

**Comment by omer-ayhan** [comment]
Hey @cortinico 👋 i would like to take `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/internal/PreparePrefabHeadersTaskTest.kt`. Thank you

**Comment by BogiKay** [comment]
Hey @cortinico, please assign me to `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/internal/PrepareJSCTaskTest.kt`

**Comment by yakupozbaydar** [comment]
Hey @cortinico , I would like to migrate `packages/react-native/ReactAndroid/src/test/java/com/facebook/react/uimanager/UIManagerModuleConstantsHelperTest.kt`
Thank you  👋

**Comment by barbarosaffan** [comment]
Hey @cortinico I can migrate `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/ReactExtensionTest.kt` if possible, thank you

**Comment by omer-ayhan** [comment]
if possible I can also take `packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/tasks/BundleHermesCTaskTest.kt` migration task as well @cortinico

**Comment by migueldaipre** [comment]
Hey @cortinico. I can migrate 

- `PrepareGlogTaskTest.kt`
- `BuildCodegenCLITaskTest.kt` 

if possible, thanks!  👋

**Comment by jaworek** [comment]
Hey @cortinico , I'll take:
- `ReactModuleInfoTest.kt`
- `DialogModuleTest.kt`
-  `BuildCodegenCLITaskTest.kt`

**Comment by migueldaipre** [comment]
Hey @cortinico. I would like to take the last one available.

`ShareModuleTest.kt`

**Comment by cortinico** [comment]
Thank you all for the great work so far! We're 75% done that's huge 🎉 

To everyone still having an open test, please try to conclude it this week 👍 

@barbarosaffan your assigned file `ReactExtensionTest.kt` was already migrated as part of another refactoring needed for 0.75, so there is no work for you to do :)

**Comment by cortinico** [comment]
Ping to @BogiKay and @Tony-MK as yours are the last 2 files. If you can't migrate them, please answer by EOD or we'll release it for the next contributor to pickup 👍

**Comment by BogiKay** [comment]
> Ping to @BogiKay and @Tony-MK as yours are the last 2 files. If you can't migrate them, please answer by EOD or we'll release it for the next contributor to pickup 👍

Hey, I'm planning to raise a PR by EOD.

**Comment by omer-ayhan** [comment]
I am also planning to finish my PR by EOD as well @cortinico

**Comment by Tony-MK** [comment]
> Ping to @BogiKay and @Tony-MK as yours are the last 2 files. If you can't migrate them, please answer by EOD or we'll release it for the next contributor to pickup 👍

Hey, I'm planning to raise a PR by EOD.

**Comment by cortinico** [comment]
Thank you all for helping us with this migration! Your contribution was extremely valuable to keep our tests clean and tidy! I hope you enjoyed contributing to React Native.

**Comment by gustavoabel** [comment]
@cortinico Thank you for the opportunity, I hope to have more chances to contribute to this amazing project.
