### ISSUE TITLE
[0.18] Things we should cherry-pick to 0.18

### ISSUE THREAD

**Issue by mkonicek** [facebook/react-native#5201]
Moving the release to Monday Jan 18 as there are quite a few things to get in plus we had an internal hackathon today on RN + Buck.

 - [x] Fix for TransformError: ... Cannot read property 'error' of null (https://github.com/facebook/react-native/issues/5191). Update: We just need to cherry-pick https://github.com/facebook/react-native/commit/5a4ee0bfaa6e6db7a105362a06fb903efa5f58a4
 - [x] Android `alert()` https://github.com/facebook/react-native/commit/1dc56a6758c58ae7608bdc130afb7b831194f7ed
 - [x] Android Proguard fix (https://github.com/facebook/react-native/commit/5f3d08d5248b47954d2739aca45c8cbbb68fc38e), support split built per architecture (https://github.com/facebook/react-native/commit/5f3d08d5248b47954d2739aca45c8cbbb68fc38e)
 - [ ] Fix StyleSheet 'textAlign' for AndroidTextInput, https://github.com/facebook/react-native/pull/4481
 - [x] 4f9086f
 - [ ] 7ecb693 - This breaks iOS, see comment on https://github.com/facebook/react-native/pull/5156
 - [x] 5a3b272
 - [x] 180fc06
 - [x] 0065986
 - [ ] Symbol polyfill: #5294, EDIT: See discussion on the PR
 - [ ] Modal: #5320, EDIT: See discussion on the PR

**Comment by satya164** [comment]
Should also cherry pick https://github.com/facebook/react-native/commit/4f9086f0e79b3594bcf0d8291e50cb0e94e93017 , https://github.com/facebook/react-native/commit/7ecb6936bc9b4e03325fd7906540a62089bc30d7 

And may be this, https://github.com/facebook/react-native/commit/5a3b272f7e989bb0e574d14c5080966a9188b674 (Flow gives lots of warnings due to this, and is almost unusable, though there are oter warnings too, this will at least decrease them)

Also in https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/ReactActivity.java , it now extends `Activity` instead of `FragmentActivity`. It will be difficult for third-party libs that require the use of `FragmentActivity` (refer https://github.com/facebook/react-native/pull/4827#issuecomment-169953931). It might also break the `DialogModule` as the commit message says that it requires `FragmentActivity` - https://github.com/facebook/react-native/commit/3a3af8a385583c7aabfad5f8ff5daa69aa29953f

PR here - #5206

**Comment by ide** [comment]
https://github.com/facebook/react-native/commit/180fc06b7a54cd48a9ed7ace661cc4cdd262a689 Fixes iOS 7

**Comment by mkonicek** [comment]
Thanks a lot guys! Commented on the PR #5206.

**Comment by jsierles** [comment]
Also should get this once it's merged. A number of people have run into it including myself:

https://github.com/facebook/react-native/pull/4481

**Comment by mkonicek** [comment]
Thanks @jsierles, added.

**Comment by skevy** [comment]
https://github.com/facebook/react-native/commit/00659864bc42f127efa07a98fe3e2bd5d4ba1d58

and

https://github.com/facebook/react-native/pull/5294

**Comment by mkonicek** [comment]
Thanks @skevy! Commented on the PR, thanks for the fix!

**Comment by Ehesp** [comment]
https://github.com/facebook/react-native/commit/18437093f2664beedd3239bb525d7daa3f2bcdbd

This would be awesome too.

**Comment by tomauty** [comment]
^ yes please

**Comment by mkonicek** [comment]
The Android Picker (https://github.com/facebook/react-native/commit/18437093f2664beedd3239bb525d7daa3f2bcdbd) is not 100% ready yet, we want to clean up the API to make it more consistent with iOS.

**Comment by mkonicek** [comment]
Releasing now. I haven't been able to cherry-pick the fix for `react-native-xcode.sh` (7ecb693), see comment on #5156.

The Android `textAlign` fix (#4481) requires a change to internal tests. We're now figuring out a way to run the Android integration tests both internally and on CircleCI and then open sourcing all of them so Android PRs can be merged more easily.

**Comment by satya164** [comment]
Closing as 0.18 is already released.
