### ISSUE TITLE
[release-0.19] Commits to cherry pick

### ISSUE THREAD

**Issue by bestander** [facebook/react-native#5462]
- [x] [HMR] Improve Hot Loading gating #5339
- [x] ~~Add an `Experiments` class to enable/disable experiments. #5446~~ (need to commment out HMR menu code)
- [x] Fix for Android split builds: https://github.com/facebook/react-native/commit/342a7630f12ec78c2849802053e83afe4d95a117
- [x] Cross-platform `AppState`: https://github.com/facebook/react-native/commit/c2d75d7a65a2bdf6e1e24a9ce887f9492be477de, https://github.com/facebook/react-native/pull/5152
- [x] Fix StyleSheet 'textAlign' for AndroidTextInput, f453e14c8f91d00a8205e6bb06094c85281b38be (#4481)
- [x] Fix Image crash on invalid source Uri 798acac18e9daab543d7b2e947bc2ed760703d99
- [x] Android Picker, ideally with the same API as iOS, 1dd5ba7021c13f3475097db5652f8f4e5e2469f1.
- [ ] Android date and time pickers, https://github.com/facebook/react-native/commit/9a0539d2c48c528d44ddb53d6ea8343890b0ddaa, Update: can't cherry-pick because would need to cherry-pick a few commits before that related to Promises which look risky.
- [x] Figure out what to do with `react-native-xcode.sh`, there's still the outstanding issue with https://github.com/facebook/react-native/commit/7ecb6936bc9b4e03325fd7906540a62089bc30d7 which we had to revert on 0.19.0-rc:. Update: this should help and probably worth cherry-picking: d3e4414( https://github.com/facebook/react-native/pull/5518), maybe even https://github.com/facebook/react-native/pull/5519 (not necessary)
- [x] Update `website/server/extractDocs.js` with the new modules and APIs so they appear on the website

New Android modules in this release: CameraRoll, AppState, Date and time pickers, Picker

**Comment by mkonicek** [comment]
0.19 is out: https://github.com/facebook/react-native/releases/v0.19.0

**Comment by bestander** [comment]
┗(｀ー´)┓  ┏(＾0＾)┛
