### ISSUE TITLE
[release-0.20] Commits to cherry pick

### ISSUE THREAD

**Issue by bestander** [facebook/react-native#5762]
- [x] added accessibility props for touchables #5346 [commit](https://github.com/facebook/react-native/commit/33d8db599ef8eb85dc27150e04c71719be6ffd26) 
- [x] Use new DisplayMetrics object in getDisplayMetrics as to not overwrite Android global state #5764 [commit](https://github.com/facebook/react-native/commit/6ac007b2ba50d5d909f09f5b4632558d1192a570)
- [x] Disable menu option for HMR f5144094955a0099d57bf3ad1439a376f46bce48
- [x] The generated proguard file is broken since 0.19 so apps built in release mode crash. It would be great to review and include #5717 #5655.[commit](https://github.com/facebook/react-native/commit/10c0758906fa071142e3ea309b2bfcbe64d7b5e0)
- [x] Disable proguard https://github.com/facebook/react-native/commit/3c74a2595abf572c38d7eeb5887c4baff47aca7c
- [ ] React-native integreted into existing android apk is giving crash in Asus Zenphone 5. react-native version used : 0.19 #5773
- [ ] minus margin broken on 0.19 #5690
- [x] Fix RCTPromise [commit](https://github.com/facebook/react-native/commit/c9a1956c4fd9cfb6bf883c835b501d097181e1a4)
- [x] Fix issue that breaks scroll views w/ RefreshControl on Android [commit](https://github.com/facebook/react-native/commit/98797177abd93d01a206fe3f4c5f31143fdebf08)
- [x] Broken multiGet [commit](https://github.com/facebook/react-native/commit/52755fdde278404540a17117098151db5f2a86e3)
- [x] Add transform-symbol-member...should have been in the preset in the first place [commit](https://github.com/facebook/react-native/commit/194092e7290c2a2e50e0263bac67686df418b915)
- [x] Versioned documentation deployment 6f1417c84982e0705912b57bf9d1aaaf1476d7d9, 7d7508e25b353ba12727525ee4d70d8884c0bc22
- [x] fix Circle CI test phase bf21002f2a7f4541091e04758cd32c97da53c893
- [x] ability to switch versions in docs website #5890 
- [x] fixed a link to android setup docs #5920
- [x] Use `getRealMetrics` for display metrics. Closes #4934 8e603940e3fca4ed2fe420c02a66d860b53f3076 
- [x] Use new DisplayMetrics object in `getDisplayMetrics` as to not overw 1ef0b8f4db54867f991262b32a35a45f7e390411
- [x] Fix DisplayMetrics KeyboardListener dependency 4254e8a0a9a9b2cfbaed6037de360420e6c268e4
- [x] Make keyboard detection more robust 5a109ae43bec251abca49a91fbd41c37e166ebbd
- [x] Expose screen metrics and window metrics 228a1fe7d48d57a0fbb2d852135ef94247198aaa

**Comment by skevy** [comment]
"Use new DisplayMetrics object in `getDispalyMetrics` as to not overwrite Android global state" https://github.com/facebook/react-native/pull/5764

**Comment by janicduplessis** [comment]
The generated proguard file is broken since 0.19 so apps built in release mode crash. It would be great to review and include #5717.

**Comment by oviava** [comment]
Would be nice to get this going https://github.com/facebook/relay/commit/60c8a76a47385d8f843e35de72d16f758689abc0 along with the dependencies

**Comment by ide** [comment]
@oviava we'll probably ship that with 0.21 or 0.22 since those PRs aren't bug fixes and also haven't been reviewed. The primary intent of the period between RC and release is to improve stability.

**Comment by oviava** [comment]
oups .. hadn't realized 20rc had been released

**Comment by mkonicek** [comment]
Maybe I was too quick to enable Proguard for everyone and we should disable it until we have an automated test on CircleCI: https://github.com/facebook/react-native/blob/master/local-cli/generator-android/templates/src/app/build.gradle#L76

**Comment by bestander** [comment]
@mkonicek regarding proguard, do you want me to create a PR and cherry pick it too?

**Comment by bestander** [comment]
Ok, created #5775

**Comment by janicduplessis** [comment]
#5784 fix issue that breaks scroll views w/ RefreshControl on Android  CLA Signed GH Review: review-needed

**Comment by daesan** [comment]
Any reason 0.20.0-rc is not published to npm?

**Comment by bestander** [comment]
Will be published once we have release notes.
Hopefully today

**Comment by skevy** [comment]
https://github.com/facebook/react-native/commit/c9a1956c4fd9cfb6bf883c835b501d097181e1a4

Fixes RCTPromise, and should make it into stable.

**Comment by skevy** [comment]
fix issue that breaks scroll views w/ RefreshControl on Android https://github.com/facebook/react-native/commit/98797177abd93d01a206fe3f4c5f31143fdebf08

**Comment by bestander** [comment]
@andreicoman11 is the display metrics bug fix ready?
Do we want to cherry-pick it into the release that is coming on Monday?

**Comment by bestander** [comment]
Not picking this PR: [Navigator][0.19.0][ios][bug]: Scene Component will render twice and more #5726

**Comment by andreicoman11** [comment]
Yep, should be good to go https://github.com/facebook/react-native/commit/228a1fe7d48d57a0fbb2d852135ef94247198aaa

**Comment by bestander** [comment]
To all interested parties: I cherry-picked all the fixes and now ready to do a release.
The 2 PR are not cherry picked because they are not resolved.

**Comment by bestander** [comment]
Closing, release in progress

**Comment by shaikhussian** [comment]
I am getting an error in RCTwebSocket.m expression result unused using react-native version-0.20.0

**Comment by bestander** [comment]
@shaikhussian, we have already moved on to 0.21.0, it is considered stable.
Do you have any problem updating to it?
