### ISSUE TITLE
[0.23] Tracking bugs in 0.23 rc, commits to cherry-pick

### ISSUE THREAD

**Issue by bestander** [facebook/react-native#6559]
rc3:

- [x] Android Modal doesn't handle the back button: https://github.com/facebook/react-native/commit/ce81f8b35af8d273072583d369594d4f5fd6d696#commitcomment-1687648, update: this is expected
- [x] Automated versioning of releases, https://github.com/facebook/react-native/pull/6625
- [x] [Android] Scale transform broken on Android, https://github.com/facebook/react-native/issues/6622

rc4:

- [x] [HMR][Packager] Fix HMR config: https://github.com/facebook/react-native/pull/6696
- [x] [Packager][Android] Fix HMR warning on Genymotion: https://github.com/facebook/react-native/pull/6594

not picked yet:

- [x] [Packager][iOS] Packager URL defaults to port 8081 if no port in bundleURL, https://github.com/facebook/react-native/commit/ac534387f81a1f15de276430246e2d3497ae48ba
- [x] [Packager] Unable to resolve assets from `node_modules`, https://github.com/facebook/react-native/commit/d0566d8bc304e9a2be1be9918b988df1f8a19594
- [x] [Website] Download links for Android NDK https://github.com/facebook/react-native/commit/ce5dce9cd5b7cceac7c1442fc9b11a2808329693
- [x] UPDATE: Not needed. [Packager] Revert strict mode in transform-es2015-modules-commonjs: https://github.com/facebook/react-native/pull/6686

**Comment by bestander** [comment]
Automated release https://github.com/facebook/react-native/pull/6625 versioning.
Would make npm deployment more robust

**Comment by bestander** [comment]
https://github.com/facebook/react-native/issues/6622

**Comment by bestander** [comment]
https://github.com/facebook/react-native/issues/6638

**Comment by bestander** [comment]
https://github.com/facebook/react-native/issues/6640

**Comment by bestander** [comment]
https://github.com/facebook/react-native/commit/ce5dce9cd5b7cceac7c1442fc9b11a2808329693 - NDK links

**Comment by bestander** [comment]
https://github.com/facebook/react-native/pull/6696 - hmr from @martinbigio

**Comment by bestander** [comment]
https://github.com/facebook/react-native/pull/6686 - revert auto strict babel plugin changes

**Comment by bestander** [comment]
Fix to https://phabricator.fb.com/D2920590, https://github.com/facebook/react-native/issues/6581 - persistent socket between packager and bridge (port problem)
