### ISSUE TITLE
[0.24] Commits to cherry pick and bugs to fix

### ISSUE THREAD

**Issue by ide** [facebook/react-native#6800]
## Known issues:

- [x] Hot module reloading raises an error: https://github.com/facebook/react-native/issues/6798
- [x] `response.json()` hangs when Chrome debugging is enabled: https://github.com/facebook/react-native/issues/6679 (fix in fcc89e9d923)
- [x] Unable to require images under `node_modules`: https://github.com/facebook/react-native/issues/6638 (fix in d0566d8bc304e9a2be1be9918b988df1f8a19594)
- [x] RefreshControl broken on iOS: https://github.com/facebook/react-native/issues/6929 (fix in https://github.com/facebook/react-native/commit/03c1688ce6fa5a6a77b25a19c1dda1a1fe62bcc3)

**Comment by ide** [comment]
Cherry-picking some fixes for iOS:
- Touch handling: https://github.com/facebook/react-native/commit/8efc098646f08efa7215c8b4368ea3438435d0e1 and https://github.com/facebook/react-native/commit/3874c012920647c63dac5a806f7faf1b7d00e5d2
- UIExplorer image demo: https://github.com/facebook/react-native/commit/a10c1b5a309586ac6b8977ccfd71ac41fd51c513

Fix HMR on Windows: https://github.com/facebook/react-native/commit/c61100d0ceb4b71c86f01f35d7464d2d8a02b342

(I'm being a little more generous with cherry picks since these are bug fixes and there is still a lot of time until the release.)

**Comment by ide** [comment]
## 0.24.0-rc2 (planned)

- Fix HMR by updating r-n-preset: https://github.com/facebook/react-native/commit/40f13742b32aac5a58e5f618b74eafebc6e4c14d
- Fix requiring images under `node_modules`: https://github.com/facebook/react-native/pull/6822

**Comment by ide** [comment]
## 0.24.0-rc3 (planned)

- [x] Use version of "react" under peerDependencies when setting up a new project: https://github.com/facebook/react-native/pull/6846

**Comment by ide** [comment]
## 0.24.0-rc4 (planned)

**Comment by ide** [comment]
## 0.23.0-rc5 (planned)

**Comment by 1ne8ight7even** [comment]
You have a typo. 0.23.0-rc5 should be 0.24.0-rc5 i think.

**Comment by ide** [comment]
Oops, thanks

**Comment by satya164** [comment]
When are we releasing the stable version? ;p

**Comment by ide** [comment]
on monday

**Comment by grabbou** [comment]
Yes, I am doing that now BTW - will be up in 3/4 hours max.

**Comment by ide** [comment]
I went ahead and pushed 0.24.0. Release notes: https://github.com/facebook/react-native/releases/tag/v0.24.0. Release progress: https://circleci.com/gh/facebook/react-native/5408.

**Comment by Benmidi** [comment]
`No compatible version found: react-native@^0.24.0`
NPM is showing version 0.23.1 as the `latest` but showing `next` as 0.25.0-rc.

**Comment by oblador** [comment]
@Benmidi: It seems the released failed at the CI.

**Comment by AndrewJack** [comment]
The Android dependency hasn't been deployed correctly. The version should be 0.24.0.
![](http://i.imgur.com/zfyTXGz.png)

**Comment by bestander** [comment]
@ide, this commit https://github.com/facebook/react-native/commit/fcc89e9d923893229dae11edb59bd3df082fafad shows only in 0.25 branch but not in 0.24.
Although in the list above it is checked.
Any ideas? Maybe GitHub just does not show the branch

**Comment by bestander** [comment]
disregard the deleted comment, I figured it out

**Comment by rickli1989** [comment]
Is this fixed ?
response.json() hangs when Chrome debugging is enabled: #6679 (fix in fcc89e9)
I still have this issue in 0.24.1
