### ISSUE TITLE
[0.27] Bugs we may want to fix

### ISSUE THREAD

**Issue by ide** [facebook/react-native#8015]
- [ ] ActivityIndicatorIOS is initially visible when it shouldn't be https://github.com/facebook/react-native/issues/7987
- [ ] Native modules cause JS to be slow https://github.com/facebook/react-native/issues/7995
- [ ] Refresh control is mispositioned https://github.com/facebook/react-native/issues/7976
- [x] Keyboard module is missing https://github.com/facebook/react-native/issues/7986

For some of these issues we don't know what the root problem or offending commit is, so they may take longer to fix if anyone has time to look into them.

cc @grabbou

**Comment by grabbou** [comment]
I've just sent out planned 0.27.2 with the keyboard fix & updated the release notes to show `how to update` as I've seen people asking Q about that.
